<?php $this->form->setAttribute('class','form-horizontal'); ?>
<div class="layout layout--three-columns">
	<section class="layout__section">
		<?=$this->form()->openTag($this->form);?>

		<div class="form-group">
			<?=$this->formLabel($form->get('name'));?>
			<?=$this->formElement($form->get('name')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('name'));?>
		</div>

		<div class="form-group">
			<?=$this->formLabel($form->get('year'));?>
			<?=$this->formElement($form->get('year')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('year'));?>
		</div>

		<div class="form-group">
			<?=$this->formLabel($form->get('body'));?>
			<?=$this->formElement($form->get('body')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('body'));?>
		</div>

		<div class="form-group">
			<?=$this->formElement(
				$form->get('submit')->setAttribute('class','btn btn-default')->setValue('Stofna')
			);?>
		</div>
		<?= $this->form()->closeTag() ?>
	</section>
	<aside class="layout__aside"></aside>
</div>


