<?php if ($this->identity): ?>
	<div class="panel panel--admin">
		<div class="panel__container">
			<div class="panel__content">
				<a href="<?=$this->url('anaegjuvogin/create');?>"><i class="fa fa-plus"></i>Stofna</a>
				<a href="<?=$this->url('anaegjuvogin/update', ['id'=>$this->entry->id]);?>"><i class="fa fa-check"></i>Uppfæra</a>
				<a href="<?=$this->url('anaegjuvogin/delete', ['id'=>$this->entry->id]);?>"><i class="fa fa-trash"></i>Eyða</a>
			</div>
		</div>
	</div>
<?php endif; ?>

<div class="panel">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__title"><h1><?=$this->entry->name?></h1></div>
				<div class="box__content"><?=$this->paragrapher($this->entry->body);?></div>
			</div>
		</div>
	</div>
</div>
