<?php
/**
 * Created by PhpStorm.
 * User: einar
 * Date: 17/03/15
 * Time: 13:16
 */


$chart = new \Stjornvisi\Lib\Pie(600,375); // \SamChristy\PieChart\PieChartImagick(600, 375);

$chart->setTitle('Browser Usage Statistics (January - April)');
// Method chaining coming soon!
$chart->addSlice('Google Chrome',   27, '#4A7EBB');
$chart->addSlice('Mozilla Firefox', 23, '#DA8137');
$chart->addSlice('Apple Safari',    11, '#9BBB59');
$chart->addSlice('Opera',            3, '#BE4B48');
$chart->addSlice('Other',            5, '#7D60A0');


?>
<html>
    <head>
        <meta charset="utf-8" />
        <style>
            body{

            }
            h1{
                color: red;
            }
        </style>
    </head>
    <body>
        <h1><?=$this->company->name?></h1>
        <h2>Starfsmenn</h2>
        <ul>
            <?php foreach($this->company->members as $member):?>
            <li>
                <h3><?=$member->name?></h3>
                <ul>
                    <?php foreach($member->attendance as $attendance): ?>
                        <li>
                            <p>Er í <?=count($attendance->groups)?> hópum</p>
                            <p><?=$attendance->from;?> - <?=$attendance->to;?></p>
                            <p>Sem héldu <?=$attendance->total?> viðburði</p>
                            <p>viðkomandi mætti á <?=$attendance->attendance?></p>
                            <img src="<?=$chart->output()?>" />
                        </li>
                    <?php endforeach;?>
                </ul>

            </li>
            <?php endforeach;?>
        </ul>
    </body>
</html>
