<?php
/**
 * Created by PhpStorm.
 * User: einarvalur
 * Date: 2/12/14
 * Time: 10:26 PM
 */
?>
<div class="layout layout--three-columns">
	<section class="layout__section">
		<div class="layout__data">
			<h1><?=$this->company->name?></h1>
			<dl class="block-property-value">
				<dt>ssn</dt>
				<dd><?=$this->company->ssn;?></dd>
				<dt>address</dt>
				<dd><?=$this->company->address;?></dd>
				<dt>zip</dt>
				<dd><?=$this->company->zip;?></dd>
				<dt>website</dt>
				<dd><?=$this->company->website;?></dd>
				<dt>number_of_employees</dt>
				<dd><?=$this->company->number_of_employees;?></dd>
				<dt>business_type</dt>
				<dd><?=$this->company->business_type;?></dd>
				<dt>safe_name</dt>
				<dd><?=$this->company->safe_name;?></dd>
				<dt>created</dt>
				<dd><?=$this->company->created->format('Y-m-d');?></dd>
			</dl>
		</div>
		<div class="layout__meta">
			<h2>Starfsmenn</h2>
			<ul class="block-list">
				<?php foreach($this->company->members as $member):?>
					<li class="block-item">
						<h3><a href="<?=$this->url('notandi/index',array('id'=>$member->id))?>"><?=$member->name;?></a></h3>
						<p><?=$member->title;?></p>

						<?php if($member->key_user):?>
							lykilstarfsmaður
							<stjonvisi-control class="inline">
								<a href="<?=$this->url('fyrirtaeki/employee-type',array('id'=>$this->company->id,'user'=>$member->id,'type'=>0))?>">Gera að starfsmanni</a>
							</stjonvisi-control>
						<?php else:?>
							starfsmaður
						<stjonvisi-control class="inline">
							<a href="<?=$this->url('fyrirtaeki/employee-type',array('id'=>$this->company->id,'user'=>$member->id,'type'=>1))?>">Gera að lykilstarfsmanni</a>
						</stjonvisi-control>
						<?php endif;?>

					</li>
				<?php endforeach;?>
			</ul>
		</div>
	</section>
	<aside class="layout__aside">
		<?php if($this->access->is_admin || $this->access->type != null):?>
			<stjonvisi-control>
				<a href="<?=$this->url('fyrirtaeki/update',array('id'=>$this->company->id))?>">Uppfæra</a>
				<?php if($this->access->is_admin || $this->access->type == 1):?>
				<a href="<?=$this->url('fyrirtaeki/delete',array('id'=>$this->company->id))?>">Eyða</a>
				<?php endif;?>
			</stjonvisi-control>
		<?php endif;?>
	</aside>
</div>
