<?php
/**
 * Created by PhpStorm.
 * User: einarvalur
 * Date: 2/12/14
 * Time: 10:26 PM
 */
?>
<div class="layout layout--three-columns page-company">
    <section class="layout__section">
        <div class="layout__data">
            <h1 class="layout__headline"><?=$this->company->name?></h1>
            <dl class="block-property-value">
                <dt>Kennitala</dt>
                <dd><?=$this->company->ssn;?></dd>
                <dt>Heimilisfang</dt>
                <dd><?=$this->company->address;?></dd>
                <dt>Póstnúmer</dt>
                <dd><?=$this->company->zip;?></dd>
                <dt>Heimasíða</dt>
                <dd><?=$this->company->website;?></dd>
                <dt>Starfsmannafjöldi</dt>
                <dd><?=$this->company->number_of_employees;?></dd>
                <dt>Rekstrarform</dt>
                <dd><?=$this->company->business_type;?></dd>
                <dt>Stofnað</dt>
                <dd><?=$this->date($this->company->created);?></dd>
                <dt>Skráðir starfsmenn</dt>
                <dd><?=count($this->company->members)?></dd>
            </dl>

            <h2 class="layout__headline">Dreifing starfsmanna</h2>
            <table class="block-table block-table--data block-table--compact">
                <thead>
                    <tr>
                        <td>Hópur</td>
                        <td class="block-table__numeric">Starfsmenn</td>
                    </tr>
                </thead>
                <tfoot></tfoot>
                <tbody>
                    <?php foreach($this->distribution as $value):?>
                    <tr>
                        <td><a href="<?=$this->url('hopur/index', array('id'=>$value->url))?>"><?=$value->name_short?></td>
                        <td class="block-table__numeric"><?=$value->group_count?></td>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>


            <h2 class="layout__headline">Mætingar á starfsári</h2>
            <?php foreach($this->attendance as $value):?>

                <table class="block-table block-table--data block-table--compact">
                    <caption>
                        <?=$value->from->format('Y')?> - <?=$value->to->format('Y')?>
                    </caption>
                    <thead>
                        <tr>
                            <td>Starfsmaður</td>
                            <td class="block-table__numeric">Mætingar</td>
                        </tr>
                    </thead>
                    <tfoot></tfoot>
                    <tbody>
                    <?php foreach($value->list as $item): ?>
                        <tr>
                            <td><a href="<?=$this->url('notandi/index', array('id'=>$item->id))?>"><?=$item->name?></a></td>
                            <td class="block-table__numeric"><?=$item->counter?></td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>

                </table>
            <?php endforeach;?>

            <!--pre>
                <?php print_r($this->attendance)?>
            </pre-->
        </div>
        <div class="layout__meta">
            <h2 class="layout__headline">Starfsmenn</h2>
            <ul class="block-list page-company__members">
                <?php foreach($this->company->members as $member):?>
                    <li class="block-item">
                        <h3><a href="<?=$this->url('notandi/index', array('id'=>$member->id))?>"><?=$member->name;?></a></h3>
                        <p><?=$member->title;?></p>
                        <p><?=$member->email;?></p>
                        <?php if($member->key_user):?>
                            <span>lykilstarfsmaður</span>
                            <stjonvisi-control class="inline">
                                <a href="<?=$this->url('fyrirtaeki/employee-type', array('id'=>$this->company->id,'user'=>$member->id,'type'=>0))?>">Gera að starfsmanni</a>
                            </stjonvisi-control>
                        <?php else:?>
                            <span>starfsmaður</span>
                        <stjonvisi-control class="inline">
                            <a href="<?=$this->url('fyrirtaeki/employee-type', array('id'=>$this->company->id,'user'=>$member->id,'type'=>1))?>">Gera að lykilstarfsmanni</a>
                        </stjonvisi-control>
                        <?php endif;?>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    </section>
    <aside class="layout__aside">
        <?php if($this->access->is_admin || $this->access->type != null):?>
            <stjonvisi-control>
                <a href="<?=$this->url('fyrirtaeki/update', array('id'=>$this->company->id))?>">Uppfæra</a>
                <?php if($this->access->is_admin || $this->access->type == 1):?>
                <a href="<?=$this->url('fyrirtaeki/delete', array('id'=>$this->company->id))?>">Eyða</a>
                <?php endif;?>
            </stjonvisi-control>
        <?php endif;?>
    </aside>
</div>
