<?php
/**
 * Created by PhpStorm.
 * User: einarvalur
 * Date: 2/12/14
 * Time: 10:05 PM
 */
?>
<h1>Fyrirtæki (<?=count($this->companies);?>)</h1>
<table>
    <thead></thead>
    <tfoot></tfoot>
    <tbody>
    <?php foreach($this->companies as $company):?>
        <tr>
            <?php if($access->is_admin):?>
            <td><a href="<?=$this->url('fyrirtaeki/index',array('id'=>$company->id))?>"><?=$company->name?></a></td>
            <?php else:?>
            <td><?=$company->name?></td>
            <?php endif;?>
            <td><?=$company->business_type?></td>
            <td><?=$company->created->format('Y-m-d')?></td>
        </tr>
    <?php endforeach;?>
    </tbody>

</table>
