<?php
    $this->form->setAttribute('class', 'form-horizontal');
?>
<div class="layout layout--three-columns">
    <section class="layout__section">

        <?=$this->form()->openTag($this->form);?>

        <div class="form-group">
            <?=$this->formLabel($form->get('boardmember_id'));?>
            <?=$this->formElement($form->get('boardmember_id')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('boardmember_id'));?>
            <p>Ef meðlimur er ekki á skrá má búa hann til <a href="<?=$this->url('stjornin/create-member')?>">hér</a></p>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('term'));?>
            <?=$this->formElement($form->get('term')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('term'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('is_chairman'));?>
            <?=$this->formElement($form->get('is_chairman')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('is_chairman'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('is_reserve'));?>
            <?=$this->formElement($form->get('is_reserve')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('is_reserve'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('is_manager'));?>
            <?=$this->formElement($form->get('is_manager')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('is_manager'));?>
        </div>
        <div class="form-group">
            <?=$this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default')->setAttribute('value', 'Stofna'));?>
        </div>
        <?= $this->form()->closeTag() ?>
    </section>
    <aside class="layout__aside"></aside>
</div>
