<?php
    $this->form->setAttribute('class', 'form-horizontal');
?>

<div class="layout layout--three-columns">
    <section class="layout__section">

        <?=$this->form()->openTag($this->form);?>

        <div class="form-group">
            <?=$this->formLabel($form->get('name'));?>
            <?=$this->formElement($form->get('name')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('name'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('email'));?>
            <?=$this->formElement($form->get('email')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('email'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('company'));?>
            <?=$this->formElement($form->get('company')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('company'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('avatar'));?>
            <?=$this->formElement($form->get('avatar')->setAttribute('class', 'form-control avatar'));?>
            <?=$this->formElementErrors($form->get('avatar'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('info'));?>
            <?=$this->formElement($form->get('info')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('info'));?>
        </div>
        <div class="form-group">
            <?=$this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default')->setAttribute('value', 'Stofna'));?>
        </div>
        <?= $this->form()->closeTag() ?>

    </section>
    <aside class="layout__aside"></aside>
</div>
