<?php
use Stjornvisi\Properties\FileProperties;

setlocale(LC_ALL,'is_IS.utf-8');
?>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 700; color: #8e8c8e;  line-height: 33px;">
						<p>Skráning á viðburð staðfest:</p>
					</td>
				</tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td align="center" bgcolor="#ffffff">
			<table class="container" border="0" cellpadding="0" cellspacing="0" width="600">
				<tr>
					<td style="font-size: 1px; line-height: 15px;" height="15">
						&nbsp; </td>
				</tr>
				<tr>
					<td align="center">
						<!-- Edit the color of Horizontal Rule -->
						<hr style="color: #428BCA; height: 1px; border: none; width: 600px; background-color: #E6E9ED;" class="hr" data-bgcolor="HR Line" width="600">
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 15px;" height="15">
						&nbsp; </td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td align="center" bgcolor="#ffffff">
			<table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
				<tr>
					<td style="font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 700; color: #353B48;  line-height: 32px;" data-size="2 Column Blog Title" data-color="2 Column Blog Title" align="left">
						<a href="/vidburdir/<?=$this->event->id;?>" style="color:Black;text-decoration:underline"><?=$this->event->subject?></a></td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 10px;" height="10">
						&nbsp;</td>
				</tr>
				<tr>
					<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #434A54; line-height: 22px;" data-size="2 Column Blog Text" data-color="2 Column Blog Text" align="left">
						<span style="font-weight:bold;color:#2b6786"><?=strftime('%e. %B', $this->event->event_date->format('U'))?>, kl. <?=$this->event->event_time->format('H:i')?> - <?=($this->event->event_end)?$this->event->event_end->format('H:i'):''?></span><br>
						<?=$this->event->location;?><br>
						<?=$this->event->address;?>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 10px;" height="10">
						&nbsp;</td>
				</tr>
				<tr>
					<td style="font-family: 'Open Sans', sans-serif; font-size: 12px; font-weight: 400; color: #434A54; line-height: 18px;" data-size="2 Column Blog Text" data-color="2 Column Blog Text" align="left">
						<?for ($i = 1; $i <= \Stjornvisi\Form\Event::MAX_PRESENTERS; ++$i):
							$field = 'presenter' . $i;
							$fieldAvatar = 'presenter' . $i . '_avatar';
							?>
							<?php if ($this->event->$field):?>
							<i class="fa fa-slideshare" title="Fyrirlesari"></i>
							<span><?=$this->event->$field?></span>
							<?php if ($this->event->$fieldAvatar):?>
								<div class="entry__image presenter_avatar">
									<?=$this->image($this->event->$fieldAvatar, FileProperties::DIR_MEDIUM, ['block-element__image']);?>
								</div>
							<?endif?>
						<?endif?>
						<?endfor;?>

						<?php foreach($this->event->groups as $group):?>
							<div style="color:#2b6786;">
								<?=$group->name?>
							</div>
						<?php endforeach;?>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 15px;" height="15">
						&nbsp;</td>
				</tr>
				<tr>
					<td align="center">
						<table align="center" border="0" cellpadding="0" cellspacing="0" bgcolor="#2b6786" style="border-radius:2px;">
							<tr>
								<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #fff; line-height: 24px; padding-left: 15px; padding-right: 15px;" height="40" align="center">
									<a href="/vidburdir/<?=$this->event->id;?>" style="color: #fff; text-decoration: none;">Nánar um viðburðinn</a>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 30px;" height="30">
						&nbsp; </td>
				</tr>
			</table>
		</td>
	</tr>
</table>