<?php
setlocale(LC_ALL, 'is_IS.utf-8');
?>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 700; color: #8e8c8e;  line-height: 33px;">
                        <p>Hjartanlega velkomin(n) í Stjórnvísi.</p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td align="center">
                        <!-- Edit the color of Horizontal Rule -->
                        <hr style="color: #428BCA; height: 1px; border: none; width: 600px; background-color: #E6E9ED;"
                            class="hr" data-bgcolor="HR Line" width="600">
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #434A54; line-height: 22px;">
                        <p>Takk fyrir að sækja um aðild að Stjórnvísi og um leið gerast félagsmaður. Vinsamlegast
                            staðfestu aðildina með því að svara þessum pósti gunnhildur@stjornvisi.is og samþykkja að
                            sendur verði reikningur fyrir félagsgjöldum.
                            <a href="https://www.stjornvisi.is/adild-og-felagsgjold">https://www.stjornvisi.is/adild-og-felagsgjold</a></p>
                        <p>Stjórnvísi er í eigu sinna félagsmanna og nú gefst öllum þeim sem starfa á þínum vinnustað
                            tækifæri til að sækja viðburði á vegum félagsins sér að kostnaðarlausu sem eru á annað
                            hundrað á ári. Meðfylgjandi er kynningarbréf til að senda á starfsmenn sem hvetur þá til að
                            skrá sig í faghópa. Faghóparnir eru tæplega 20 og í hverjum faghópi eru kraftmiklar stjórnir
                            sem setja mikla vinnu og metnað í sína dagskrá. Tæplega 300 fyrirtæki eru í Stjórnvísi og
                            félagar 3.500. <a href="https://www.stjornvisi.is/fyrirtaeki">https://www.stjornvisi.is/fyrirtaeki</a></p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td align="center">
                        <!-- Edit the color of Horizontal Rule -->
                        <hr style="color: #428BCA; height: 1px; border: none; width: 600px; background-color: #E6E9ED;"
                            class="hr" data-bgcolor="HR Line" width="600">
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 700; color: #8e8c8e;  line-height: 33px;">
                        <p>Kynningarbréf til starfsmanna</p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 18px; font-weight: 700; color: #222;  line-height: 26px;">
                        <p>Vinnustaðurinn þinn er aðili að Stjórnvísi - og allir geta verið með!</p>
                    </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #434A54; line-height: 22px;">
                        <p>Okkur langar að vekja athygli á að þar sem <b>vinnustaðurinn þinn</b> er aðili að Stjórnvísi,
                            geta allir stjórnendur í fyrirtækinu og áhugasamir starfsmenn um stjórnun, sótt fundi í
                            faghópum félagsins sér að kostnaðarlausu. Virk þátttaka starfsmanna í Stjórnvísi gefur þeim
                            færi á hagstæðri símenntun og praktískum umræðum um stjórnun. Skráning í faghópana fer fram
                            á heimasíðu Stjórnvísi www.stjornvisi.is <b>„Stofna aðgang“</b>. Þar seturðu inn nafn, netfang,
                            starfstitil, tengir þig síðan við vinnustaðinn þinn sem er nú þegar til á skrá og velur þér
                            lykilorð. Að því loknu velur þú þér þá faghópa sem þú vilt vera skráður í. Þeir sem skrá sig
                            í mannauðsstjórnunarhópinn fá póstsendingar um alla viðburði. Á heimasíðu Stjórnvísi
                            www.stjornvisi.is eru upplýsingar um viðburði faghópa, ráðstefnur og áhugaverðar greinar.
                            Árlega eru haldnir yfir 100 viðburðir og ráðstefnur á vegum félagsins sem er fríir öllum
                            starfsmönnum þar sem vinnustaðurinn hefur greitt árgjald til félagsins.</p>
                        <p><b>Ávinningurinn af því að vera í Stjórnvísi!</b></p>
                        <ol>
                            <li>Hagstæð símenntun um stjórnun sem byggir fyrst og fremst á raunhæfum dæmum úr atvinnulífinu.</li>
                            <li>Sterkt tengslanet.</li>
                            <li>Virkt félagsstarf.</li>
                            <li>Ókeypis aðgangur að faghópum, ráðstefnum, fundum og viðburðum um stjórnun á vegum félagsins.</li>
                        </ol>
                        <ul>
                            <li><b>Stjórnvísi</b> er stærsta stjórnunarfélag á Íslandi með 3.500 virka félagsmenn og um 300 fyrirtæki innan sinna raða. Félagið er sterkt og öflugt tengslanet fyrir félagsmenn.</li>
                            <li><b>Stjórnvísi</b> er opið öllum einstaklingum, fyrirtækjum og stofnunum sem hafa áhuga á stjórnun; eins og stjórnendum, sérfræðingum, nemendum og öðrum áhugamönnum um stjórnun.</li>
                            <li><b>Stjórnvísi</b> býður hagstæðustu símenntunina um stjórnun á markaðnum.</li>
                            <li><b>Stjórnvísi</b> er með kjarnastarf sitt í kraftmiklum faghópum félagsmanna en jafnframt stendur félagið fyrir almennum ráðstefnum, viðburðum og verðlaunum um stjórnun.</li>
                            <li><b>Stjórnvísi</b> er áhugamannafélag í eigu félagsmanna og starfar ekki með fjárhagslegan ágóða í huga.</li>
                        </ul>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #434A54; line-height: 22px;">
                        <p><b>Bestu kveðjur,</b><br>
                        Gunnhildur Arnardóttir, framkvæmdastjóri Stjórnvísi</p>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>