<?php
use Stjornvisi\Properties\FileProperties;

setlocale(LC_ALL, 'is_IS.utf-8');
$paragrapher = new \Stjornvisi\View\Helper\Paragrapher();
?>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td align="center">
                        <!-- Edit the color of Horizontal Rule -->
                        <hr style="color: #428BCA; height: 1px; border: none; width: 600px; background-color: #E6E9ED;"
                            class="hr" data-bgcolor="HR Line" width="600">
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 700; color: #353B48;  line-height: 32px;"
                        data-size="2 Column Blog Title" data-color="2 Column Blog Title" align="left">
                        <a href="/vidburdir/<?= $this->event->id; ?>"
                           style="color:Black;text-decoration:underline"><?= $this->event->subject ?></a></td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 10px;" height="10">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #434A54; line-height: 22px;"
                        data-size="2 Column Blog Text" data-color="2 Column Blog Text" align="left">
                        <span style="font-weight:bold;color:#2b6786"><?= strftime('%e. %B', $this->event->event_date->format('U')) ?>
                            , kl. <?= $this->event->event_time->format('H:i') ?>
                            - <?= ($this->event->event_end) ? $this->event->event_end->format('H:i') : '' ?></span><br>
                        <?= $this->event->location; ?><br>
                        <?= $this->event->address; ?>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 10px;" height="10">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 12px; font-weight: 400; color: #434A54; line-height: 18px;"
                        data-size="2 Column Blog Text" data-color="2 Column Blog Text" align="left">
                        <?php foreach ($this->event->groups as $group): ?>
                            <div style="color:#2b6786;margin-bottom: 10px;">
                                <a href="/hopur/<?= $group->url ?>"><?= $group->name ?></a>
                            </div>
                        <?php endforeach; ?>

                        <p><?= $this->event->body ?></p>

                        <table width="100%">
                            <tr>
                                <?php for ($i = 1; $i <= \Stjornvisi\Form\Event::MAX_PRESENTERS; ++$i):
                                    $field = 'presenter' . $i;
                                    $fieldAvatar = 'presenter' . $i . '_avatar';
                                    ?>
                                    <td width="33.33%" valign="top" align="center">
                                    <?php if (isset($event->$field) && $event->$field): ?>
                                    <?php if (isset($event->$fieldAvatar) && $event->$fieldAvatar): ?>
                                        <div style="text-align:center;font-size: 12px;">
                                            <?= $this->image($event->$fieldAvatar, FileProperties::DIR_MEDIUM, ['responsive']); ?>
                                            <span><?= $event->$field ?></span>
                                        </div>
                                    <?php endif; ?>
                                    </td>
                                <?php endif; ?>
                                <?php endfor; ?>
                            </tr>
                        </table>
                        <style>
                            img.responsive {
                                max-width: 150px;
                                height: auto;
                                margin: 0 auto 15px;
                            }</style>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td align="center">
                        <table align="center" border="0" cellpadding="0" cellspacing="0" bgcolor="#2b6786"
                               style="border-radius:2px;">
                            <tr>
                                <td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #fff; line-height: 24px; padding-left: 15px; padding-right: 15px;"
                                    height="40" align="center">
                                    <a href="/vidburdir/<?= $this->event->id; ?>"
                                       style="color: #fff; text-decoration: none;">Nánar um viðburðinn</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td align="center">
                        <!-- Edit the color of Horizontal Rule -->
                        <hr style="color: #428BCA; height: 1px; border: none; width: 600px; background-color: #E6E9ED;"
                            class="hr" data-bgcolor="HR Line" width="600">
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td align="center" style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #434A54; line-height: 22px;">
                        <?php $date_start = urlencode($event->event_date->format('Y-m-d').' '.$this->event->event_time->format('H:i:s'))?>
                        <?php $date_end = urlencode($event->event_date->format('Y-m-d').' '.$this->event->event_end->format('H:i:s'))?>
                        <?php $timezone = urlencode($event->event_date->format('e'))?>
                        <?php $location = urlencode($event->location)?>
                        <?php $subject = urlencode($event->subject)?>
                        <?php $body = urlencode($event->body)?>
                        <?php $params = "?f=m&e[0][date_start]=$date_start&e[0][date_end]=$date_end&e[0][timezone]=$timezone&e[0][title]=$subject&e[0][description]=$body&e[0][location]=$location&e[0][organizer]=Stjórnvísi&e[0][organizer_email]=stjornvisi@stjornvisi.is&e[0][privacy]=public"?>
                        <p>Settu viðburðinn á dagatalið þitt:</p>
                        <a id="fl_ical" href="http://addtocalendar.com/atc/ical<?=$params?>" target="_blank">iCalendar</a> &bull;
                        <a id="fl_google" href="http://addtocalendar.com/atc/google<?=$params?>" target="_blank">Google Calendar</a> &bull;
                        <a id="fl_outlook" href="http://addtocalendar.com/atc/outlook<?=$params?>" target="_blank">Outlook</a> &bull;
                        <a id="fl_outlookonline" href="http://addtocalendar.com/atc/outlookonline<?=$params?>" target="_blank">Outlook Online</a> &bull;
                        <a id="fl_yahoo" href="http://addtocalendar.com/atc/yahoo<?=$params?>" target="_blank">Yahoo! Calendar</a>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
