<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td align="center" bgcolor="#ffffff">
			<table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
				<tr>
					<td style="font-size: 1px; line-height: 30px;" height="30">
						&nbsp; </td>
				</tr>
				<tr>
					<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #353B48; line-height: 24px;">
						<p>Sæl(l) <?=$this->user->name?></p>
						<?=$this->body;?>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 30px;" height="30">
						&nbsp; </td>
				</tr>
				<tr>
					<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #353B48; line-height: 24px;">
						<dl>
							<dt>Hópur</dt>
							<dd><?=$this->group->name?></dd>
						</dl>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 15px;" height="15">
						&nbsp; </td>
				</tr>
			</table>
		</td>
	</tr>
</table>
