<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td align="center" bgcolor="#ffffff">
			<table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
				<tr>
					<td style="font-size: 1px; line-height: 30px;" height="30">
						&nbsp; </td>
				</tr>
				<tr>
					<td style="font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 700; color: #8e8c8e;  line-height: 33px;">
						<p>Afskráning úr hóp staðfest:</p>
					</td>
				</tr>
				<tr>
					<t<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #353B48; line-height: 24px;">
						<p>Þú hefur ákveðið að afskrá þig úr hópnum <strong><?=$this->group->name?></strong></p>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
