<?php

setlocale(LC_ALL, 'is_IS.utf-8');
$paragrapher = new \Stjornvisi\View\Helper\Paragrapher();
?>
<table data-module="image-notice" align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<!--  Change Full Width BG Color -->
		<td data-bgcolor="Image Notice BG" align="center" bgcolor="#ffffff"
			style="background-color: rgb(255, 255, 255);">
			<table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
				<tr>
					<td height="20">
					</td>
				</tr>
				<tr>
					<td style="font-family: 'Open Sans', sans-serif; font-size: 20px; font-weight: 700; color: #8e8c8e;  line-height: 33px;"
						data-size="Module Main Title" data-color="Module Main Title" align="left">
						Vikan <strong><?=strftime('%e. %b %Y', $this->from->format('U'))?>
							- <?=strftime('%e. %b %Y', $this->to->format('U'))?></strong> hjá Stjórnvísi
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%"
	   style="position: relative; opacity: 1; z-index: 0;">
	<?for ($i=0, $iMax = count($this->events); $i < $iMax; $i += 2):?>
	<?$event1 = $this->events[$i];?>
	<tr>
		<!--  Change Full Width BG Color -->
		<td data-bgcolor="2 Column Blog BG" align="center" bgcolor="#ffffff">
			<table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
				<tr>
					<td style="font-size: 1px; line-height: 30px;" height="30">&nbsp;</td>
				</tr>
				<tr>
					<td>
						<table width="287" class="twelve" align="left"
							   style="width:287px;border-collapse:collapse; mso-table-lspace:0; mso-table-rspace:0;"
							   border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 600; color: Black; line-height: 22px;text-transform: capitalize">
									<span
										style="color:#ff9900"><?=strftime('%A', $event1->event_date->format('U'))?></span>
									kl. <?=$event1->event_time->format('H:i')?>:
								</td>
							</tr>
							<tr>
								<td style="font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 700; color: #353B48;  line-height: 32px;"
									data-size="2 Column Blog Title" data-color="2 Column Blog Title" align="left">
									<a href="/vidburdir/<?=$event1->id;?>"
									   style="color:Black;text-decoration:underline"><?=$event1->subject?></a></td>
							</tr>
							<tr>
								<td style="font-size: 1px; line-height: 10px;" height="10">
									&nbsp;</td>
							</tr>
							<tr>
								<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #434A54; line-height: 22px;"
									data-size="2 Column Blog Text" data-color="2 Column Blog Text" align="left">
									<span style="font-weight:bold;color:#2b6786">
										<?=strftime('%e. %B', $event1->event_date->format('U'))?>, kl. <?=$event1->event_time->format('H:i')?>
										- <?=($event1->event_end) ? $event1->event_end->format('H:i') : ''?></span><br>
									<?=$event1->location;?><br>
									<?=$event1->address;?>
								</td>
							</tr>
							<tr>
								<td style="font-size: 1px; line-height: 10px;" height="10">
									&nbsp;</td>
							</tr>
							<tr>
								<td style="font-family: 'Open Sans', sans-serif; font-size: 12px; font-weight: 400; color: #434A54; line-height: 18px;"
									data-size="2 Column Blog Text" data-color="2 Column Blog Text" align="left">
									<?=$paragrapher(mb_substr($event1->body, 0, 200, 'utf-8') . '&#8230;')?>

									<?php foreach ($event1->groups as $group): ?>
										<div style="color:#2b6786;">
											<a href="/hopur/<?=$group->url?>"><?=$group->name?></a>
										</div>
									<?php endforeach; ?>
								</td>
							</tr>
							<tr>
								<td style="font-size: 1px; line-height: 15px;" height="15">
									&nbsp;</td>
							</tr>
							<tr>
								<td>
									<table border="0" cellpadding="0" cellspacing="0" bgcolor="#2b6786"
										   style="border-radius:2px;">
										<tr>
											<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #fff; line-height: 24px; padding-left: 15px; padding-right: 15px;"
												height="40" align="center">
												<a href="/vidburdir/<?=$event1->id;?>"
												   style="color: #fff; text-decoration: none;">Nánar um viðburðinn</a>
											</td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td style="font-size: 1px; line-height: 30px;" height="30">
									&nbsp; </td>
							</tr>
						</table>
						<!-- SPACE -->
						<table class="twelve"
							   style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"
							   align="left" border="0" cellpadding="0" cellspacing="0" width="1">
							<tr>
								<td style="font-size: 60px; line-height: 60px;" height="60" width="1">
								</td>
							</tr>
						</table>
						<!-- END SPACE -->
						<?php if (isset($this->events[$i+1])): ?>
							<?$event2 = $this->events[$i+1];?>
							<table class="twelve"
								   style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"
								   align="right" border="0" cellpadding="0" cellspacing="0" width="287">
								<tr>
									<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 600; color: Black; line-height: 22px;text-transform: capitalize">
										<span
											style="color:#ff9900"><?=strftime('%A', $event2->event_date->format('U'))?></span>
										kl. <?=$event2->event_time->format('H:i')?>:
									</td>
								</tr>
								<tr>
									<td style="font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 700; color: #353B48;  line-height: 32px;"
										data-size="2 Column Blog Title" data-color="2 Column Blog Title" align="left">
										<a href="/vidburdir/<?=$event2->id;?>"
										   style="color:Black;text-decoration:underline"><?=$event2->subject?></a></td>
								</tr>
								<tr>
									<td style="font-size: 1px; line-height: 10px;" height="10">
										&nbsp;</td>
								</tr>
								<tr>
									<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #434A54; line-height: 22px;"
										data-size="2 Column Blog Text" data-color="2 Column Blog Text" align="left">
									<span style="font-weight:bold;color:#2b6786">
										<?=strftime('%e. %B', $event2->event_date->format('U'))?>, kl. <?=$event2->event_time->format('H:i')?>
										- <?=($event2->event_end) ? $event2->event_end->format('H:i') : ''?></span><br>
										<?=$event2->location;?><br>
										<?=$event2->address;?>
									</td>
								</tr>
								<tr>
									<td style="font-size: 1px; line-height: 10px;" height="10">
										&nbsp;</td>
								</tr>
								<tr>
									<td style="font-family: 'Open Sans', sans-serif; font-size: 12px; font-weight: 400; color: #434A54; line-height: 18px;"
										data-size="2 Column Blog Text" data-color="2 Column Blog Text" align="left">
										<?=$paragrapher(mb_substr($event2->body, 0, 200, 'utf-8') . '&#8230;')?>

										<?php foreach ($event2->groups as $group): ?>
											<div style="color:#2b6786;">
												<a href="/hopur/<?=$group->url?>"><?=$group->name?></a>
											</div>
										<?php endforeach; ?>
									</td>
								</tr>
								<tr>
									<td style="font-size: 1px; line-height: 15px;" height="15">
										&nbsp;</td>
								</tr>
								<tr>
									<td>
										<table border="0" cellpadding="0" cellspacing="0"
											   bgcolor="#2b6786"
											   style="border-radius:2px;">
											<tr>
												<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #fff; line-height: 24px; padding-left: 15px; padding-right: 15px;"
													height="40" align="center">
													<a href="/vidburdir/<?=$event2->id;?>"
													   style="color: #fff; text-decoration: none;">Nánar um
														viðburðinn</a>
												</td>
											</tr>
										</table>
									</td>
								</tr>
								<tr>
									<td style="font-size: 1px; line-height: 30px;" height="30">
										&nbsp; </td>
								</tr>
							</table>
							<?unset($event2);?>
						<?php endif ?>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 50px;" height="50">
						&nbsp;</td>
				</tr>
			</table>
		</td>
	</tr>
	<?endfor;?>
</table>
<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td data-bgcolor="HR BG" align="center" bgcolor="#ffffff">
			<table class="container" border="0" cellpadding="0" cellspacing="0" width="600">
				<tr>
					<td align="center">
						<!-- Edit the color of Horizontal Rule -->
						<hr style="color: #428BCA; height: 1px; border: none; width: 600px; background-color: #E6E9ED;"
							class="hr" data-bgcolor="HR Line" width="600">
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td align="center" bgcolor="#ffffff">
			<table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
				<tr>
					<td style="font-size: 1px; line-height: 50px;" height="50">
						&nbsp;</td>
				</tr>
				<tr>
					<td>
						<table class="twelve"
							   style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"
							   align="right" border="0" cellpadding="0" cellspacing="0" width="287">
							<tr>
								<td align="center">
									<img src="/stjornvisi/stylesheets/images/stjornvisi-logo-square.jpg" alt=""
										 class="full"
										 width="287">
								</td>
							</tr>
						</table>
						<!-- SPACE -->
						<table class="twelve"
							   style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"
							   align="right" border="0" cellpadding="0" cellspacing="0" width="1">
							<tr>
								<td style="font-size: 20px; line-height: 20px;" height="40" width="1">
								</td>
							</tr>
						</table>
						<!-- END SPACE -->
						<table class="twelve"
							   style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"
							   align="left" border="0" cellpadding="0" cellspacing="0" width="287">
							<tr>
								<td style="font-family: 'Open Sans', sans-serif; font-size: 20px; font-weight: 700; color: #353B48;  line-height: 24px;"
									align="left">
									Faghópar Stjórnvísi
								</td>
							</tr>
							<tr>
								<td style="font-size: 1px; line-height: 10px;" height="10">
									&nbsp;</td>
							</tr>
							<tr>
								<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 700; color:#2b6786;  line-height: 18px;"
									align="left">
									20 virkir faghópar
								</td>
							</tr>
							<tr>
								<td style="font-size: 1px; line-height: 15px;" height="15">
									&nbsp;</td>
							</tr>
							<tr>
								<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #353B48; line-height: 24px;"
									align="left">
									Kynntu þér fjölbreytta flóru faghópa Stjórnvísi. Starfið byggist á viðburðum, en
									fleiri virkir meðlimir í faghópum eflir starfið. Vilt þú starfa með í faghópi? Láttu
									þína rödd heyrast!
								</td>
							</tr>
							<tr>
								<td style="font-size: 1px; line-height: 15px;" height="15">
									&nbsp;</td>
							</tr>
							<tr>
								<td align="left">
									<table align="left" border="0" cellpadding="0" cellspacing="0" bgcolor="#2b6786"
										   style="border-radius:2px;">
										<tr>
											<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #fff; line-height: 24px; padding-left: 15px; padding-right: 15px; text-align: center;"
												height="40" align="center">
												<a href="https://www.stjornvisi.is"
												   style="color: #fff; text-decoration:none;">Skoða faghópa á
													stjornvisi.is</a>
											</td>
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 50px;" height="50">
						&nbsp;</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<!--  Change Full Width BG Color -->
		<td align="center" bgcolor="#ffffff">
			<table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
				<tr>
					<td style="font-size: 1px; line-height: 30px;" height="30">
						&nbsp; </td>
				</tr>
				<tr>
					<td style="font-family: 'Open Sans', sans-serif; font-size: 25px; font-weight: 700; color:#2b6786;  line-height: 25px;"
						align="center">
						<?=$this->news->title?>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 15px;" height="15">
						&nbsp; </td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 10px;" height="10">
						&nbsp; </td>
				</tr>
				<tr>
					<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #353B48; line-height: 24px;"
						data-size="Notice Center Text" data-color="Notice Center Text" align="center">
						<?=$paragrapher(mb_substr($this->news->body, 0, 200, 'utf-8') . '&#8230;')?>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 10px;" height="15">
						&nbsp; </td>
				</tr>
				<tr>
					<td align="center">
						<table align="center" border="0" cellpadding="0" cellspacing="0" bgcolor="#2b6786"
							   style="border-radius:2px;">
							<tr>
								<td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #fff; line-height: 24px; padding-left: 15px; padding-right: 15px;"
									height="40" align="center">
									<a href="https://www.stjornvisi.is/frettir/<?=$this->news->id?>"
									   style="color: #fff; text-decoration:none;">Lesa
										frétt á stjornvisi.is</a>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="font-size: 1px; line-height: 30px;" height="30">
						&nbsp; </td>
				</tr>
			</table>
		</td>
	</tr>
</table>