
<h1>Sæl(l) <?=$this->user->name;?></h1>

<p>Vikan <?=$this->from->format('d. M Y')?> - <?=$this->to->format('d. M Y')?> framundan hjá Stjórnvísi</p>

<table style="width:100%" border=0>
	<tr>
		<?php foreach ($this->events as $event):?>
		<td style="padding:5px;" valign="top">
			<h2><?=$event->subject?></h2>
			<h3><?=$event->event_date->format('d. M Y');?> | <?=$event->event_time->format('H:i');?> - <?=$event->event_end->format('H:i');?></h3>
			<?=$event->body;?>
			<dl style="background:#f1f1f1;border:1px solid #e2dfdf;padding:10px">
				<dt><strong>Faghópar</strong></dt>
				<dd>
					<ul style="list-style-type:none;margin:0;padding:0">
						<?php foreach($event->groups as $group):?>
						<li><a href="http://stjornvisi.is/vidburdir/<?=$group->url?>"><?=$group->name_short?></a></li>
						<?php endforeach;?>
					</ul>
				</dd>
				<dt><strong>Viðburður</strong></dt>
				<dd><?=$event->subject;?></dd>
				<dt><strong>Staður</strong></dt>
				<dd><?=$event->location;?></dd>
				<dt><strong>Tími</strong></dt>
				<dd><?=$event->event_date->format('d. M Y');?> | <?=$event->event_time->format('H:i');?><?php if($event->event_end):?> - <?=$event->event_end->format('H:i');?><?php endif;?></dd>
				<dt><strong>Skráning</strong></dt>
				<dd><a href="http://www.stjornvisi.is/vidburdir/<?=$event->id;?>" target="_blank">http://www.stjornvisi.is/vidburdir/<?=$event->id;?></a></dd>
			</dl>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<?php endforeach;?>
</table>
