<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #353B48; line-height: 24px;">
                        <p>Sæl(l) <?=$this->user->name?></p>
                        <p>Þú hefur fengið þennann póst vegna þess að þú hefur óskað eftir að tengja Stjórnvísis-aðganginn
                            þinn við Facebook.</p>
                        <p>Það eina sem þú átt eftir að gera er að smella á hlekkinn hér fyrir neðan til að Facebook
                            geti staðfest að þú viljir nota aðganginn þinn. Eftir það verður þú sjálfkrafa send(ur)
                            á heimasíðu Stjórnvísi</p>
                        <a href="<?=$this->link?>"><?=$this->link?></a>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

