<?php
setlocale(LC_ALL, 'is_IS.utf-8');
?>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 24px; font-weight: 700; color: #8e8c8e;  line-height: 33px;">
                        <p>Hjartanlega velkomin(n) í Stjórnvísi.</p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td align="center">
                        <!-- Edit the color of Horizontal Rule -->
                        <hr style="color: #428BCA; height: 1px; border: none; width: 600px; background-color: #E6E9ED;"
                            class="hr" data-bgcolor="HR Line" width="600">
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #434A54; line-height: 22px;">
                        <p>Við óskum þér til hamingju með skráningu í Stjórnvísi, stærsta stjórnunarfélagi á Íslandi. Þátttaka þín í félaginu styrkir starfið.</p>
                        <p>Næsta skref hjá þér er að skrá þig í einn eða fleiri faghópa og í framhaldinu færðu sent yfirlit yfir dagskrá vikunnar á sunnudögum.</p>
                        <p>Kynntu þér þá faghópa sem eru í boði:<br />
                            <a href="https://www.stjornvisi.is/hopur">https://www.stjornvisi.is/hopur</a></p>
                        <p>Hlökkum til að sjá þig á viðburðum á næstunni!</p>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>