<table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td align="center" bgcolor="#ffffff">
            <table class="container" align="center" border="0" cellpadding="0" cellspacing="0" width="600">
                <tr>
                    <td style="font-size: 1px; line-height: 30px;" height="30">
                        &nbsp; </td>
                </tr>
                <tr>
                    <td style="font-family: 'Open Sans', sans-serif; font-size: 13px; font-weight: 400; color: #353B48; line-height: 24px;">
                        <p>Við óskum þér til hamingju með skráningu í Stjórnvísi, stærsta stjórnunarfélagi á Íslandi. Þátttaka þín í félaginu styrkir starfið.</p>
                        <p>Næsta skref hjá þér er að skrá þig í einn eða fleiri faghópa og í framhaldinu færðu sent yfirlit yfir dagskrá vikunnar á sunnudögum.</p>
                        <p>Kynntu þér þá faghópa sem eru í boði:<br />
                            <a href="https://www.stjornvisi.is/hopur">https://www.stjornvisi.is/hopur</a></p>
                        <p>Hlökkum til að sjá þig á viðburðum á næstunni!</p>
                        <?php if ($this->company):?>
                            <p>ATHUGIÐ:</p>
                            <p>Með skráningu þinni var stofnað nýtt fyrirtæki: <?=$this->company->name?></p>
                            <p>Greitt er fyrir aðild fyrirtækisins skv. gjaldskrá:<br />
                                <a href="https://www.stjornvisi.is/adild-og-felagsgjold">https://www.stjornvisi.is/adild-og-felagsgjold</a></p>
                            <p>Sé um mistök að ræða óskum við góðfúslega eftir að þessum pósti sé
                                svarað með viðeigandi upplýsingum, svo ekki komi til útgáfu reiknings.</p>
                        <?php endif?>
                    </td>
                </tr>
                <tr>
                    <td style="font-size: 1px; line-height: 15px;" height="15">
                        &nbsp; </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

