<?php
/**
 * Created by PhpStorm.
 * User: einar
 * Date: 18/01/15
 * Time: 01:53
 */
?>
<p>Sæl(l) <?=$this->user->name?></p>
<p>Þú hefur fengið þennann póst vegna þess að þú hefur óskað eftir að tengja Stjónvísisaðganginn
	þinn við Facebook.</p>
<p>Það eina sem þú átt eftir að gera er að smella á hlekkinn hér fyrir neðan til að Facebook
	geti staðfest að þú viljir nota aðganginn þinn. Eftir það verður þú sjálfkrafa send(ur)
	á heimasíðu Stjónvísi</p>
<a href="<?=$this->link?>"><?=$this->link?></a>