<div class="layout_article">
	<article class="block-element">
		<header class="block-element__header">
			<time class="block-element__time" datetime="<?=$this->news->created_date->format('c')?>">
				<?=$this->date($this->news->created_date,\Stjornvisi\View\Helper\Date::FORMAT_DATE_TIME)?>
			</time>
			<h1><?=$this->news->title?></h1>
			<ul class="block-element__tags">
				<li>
				<?php if($this->news->group):?>
					<a href="<?=$this->url('hopur/index',array('id'=>$this->news->group->url)) ?>"><?=$this->news->group->name_short;?></a>
				<?php else:?>
					<span>Stjórnvísisfrétt</span>
				<?php endif;?>
				</li>
			</ul>
		</header>
		<section class="block-element__body">
			<?php if($this->news->avatar):?>
				<img class="block-element__image" src="<?=$this->basePath("/images/300/{$this->news->avatar}")?>" />
			<?php endif;?>
			<?=$this->paragrapher($this->news->body);?>
		</section>
		<aside class="block-element__aside">
			<?php if($this->news->group):?>
				<a href="<?=$this->url('hopur/index',array('id'=>$this->news->group->url)) ?>"><?=$this->news->group->name_short;?></a>
			<?php else:?>
				<span>Stjórnvísisfrétt</span>
			<?php endif;?>
		</aside>
		<footer class="block-element__footer"></footer>
	</article>
</div>





