<?php if($this->access->is_admin || $this->access->type >= 1):?>
	<div class="btn-group">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			Action <span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu">
			<li><a href="<?=$this->url('frettir/update',array('id'=>$this->news->id));?>" class="control-update">Uppfæra</a></li>
			<li><a href="<?=$this->url('frettir/delete',array('id'=>$this->news->id));?>">Eyða</a></li>
		</ul>
	</div>
<?php endif;?>
<h1>Tengdar fréttir</h1>
<ul>
	<?php foreach($this->related as $news):?>
		<li class="news">
			<time><?=$news->created_date->format('Y-m-d H:i')?></time>
			<?php if( $news->avatar ): ?>
			<a href="<?=$this->url('frettir/index',array('id'=>$news->id))?>">
				<img src="<?=$this->basePath("/images/300/{$news->avatar}")?>" />
			</a>
			<?php endif;?>
			<h2><a href="<?=$this->url('frettir/index',array('id'=>$news->id))?>"><?=$news->title?></a></h2>
		</li>
	<?php endforeach;?>
</ul>