<?php
    $this->form->setAttribute('class', 'form-horizontal');
?>
<div class="layout layout--three-columns">
    <section class="layout__section">
        <?=$this->form()->openTag($this->form);?>

        <div class="form-group">
            <?=$this->formLabel($form->get('title'));?>
            <?=$this->formElement($form->get('title')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('title'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('summary'));?>
            <?=$this->formElement($form->get('summary')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('summary'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('body'));?>
            <?=$this->formElement($form->get('body')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('body'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('venue'));?>
            <?=$this->formElement($form->get('venue')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('venue'));?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('authors'));?>
            <?=$this->formElement($form->get('authors')->setAttribute('class', 'form-control'));?>
            <?=$this->formElementErrors($form->get('authors'));?>
        </div>
        <div class="form-group">
            <?=$this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default'));?>
        </div>
        <?= $this->form()->closeTag() ?>
    </section>
    <aside class="layout__aside"></aside>
</div>


