<?php
$this->form->setAttribute('class','form-horizontal');
?>

<div class="layout layout--three-columns">
	<section class="layout__section">
	<div class="layout__data">
<?=$this->form()->openTag($this->form);?>

<div class="form-group">
<?=$this->formLabel($form->get('password'));?>
<?=$this->formElement($form->get('password')->setAttribute('class','form-control'));?>
<?=$this->formElementErrors($form->get('password'));?>
</div>
    <div class="form-group">
<?=$this->formLabel($form->get('password-again'));?>
<?=$this->formElement($form->get('password-again')->setAttribute('class','form-control'));?>
<?=$this->formElementErrors($form->get('password-again'));?>
        </div>

    <div class="form-group">
        <?=$this->formElement(
			$form->get('submit')->setAttribute('class','btn btn-default')->setValue('Uppfæra')
		);?>
    </div>

<?= $this->form()->closeTag() ?>
		</div>
		<div class="layout__meta">&nbsp;</div>
	</section>
	<aside class="layout__aside"></aside>
</div>