<div class="panel">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__content">
					<?php if($this->message):?>
						<div>
							Tengingar hafa verið uppfærðar.
						</div>
					<?php endif;?>
					<?php $this->form->setAttribute('class', 'form-horizontal');?>
					<?=$this->form()->openTag($this->form);?>

					<div class="form-group">
						<?=$this->formLabel($form->get('groups'));?>
						<div class="checkbox">
							<?=$this->formMultiCheckbox($form->get('groups'));?>
							<?=$this->formElementErrors($form->get('groups'));?>
						</div>
					</div>

					<div class="form-group">
						<?=$this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default')->setValue('Uppfæra'));?>
					</div>

					<?= $this->form()->closeTag() ?>
				</div>
			</div>
		</div>
	</div>
</div>
