<?php
/**
 * Created by PhpStorm.
 * User: einar
 * Date: 23/09/14
 * Time: 13:50
 */
?>
<div class="layout layout--three-columns">
	<section class="layout__section">

		<?php if($this->message):?>
			<div>
				Tengingar hafa verið uppfærðar.
			</div>
		<?php endif;?>
		<?php $this->form->setAttribute('class','form-horizontal');?>
		<?=$this->form()->openTag($this->form);?>

		<div class="form-group">
			<?=$this->formLabel($form->get('groups'));?>
			<div class="checkbox">
				<?=$this->formMultiCheckbox($form->get('groups'));?>
				<?=$this->formElementErrors($form->get('groups'));?>
			</div>
		</div>

		<div class="form-group">
			<?=$this->formElement(
				$form->get('submit')->setAttribute('class','btn btn-default')->setValue('Uppfæra')
			);?>
		</div>

		<?= $this->form()->closeTag() ?>

	</section>
	<aside class="layout__aside"></aside>
</div>
