<?php
/**
 * Created by PhpStorm.
 * User: einarvalur
 * Date: 2/18/14
 * Time: 5:47 PM
 */

	$stack = array_chunk( $this->users, ceil(count($this->users)/2) );

?>

<div class="default-wrapper">
	<h1>Notendur (<?=count($this->users)?>)</h1>
	<div class="row">
	<?php foreach( $stack as $chunk ): ?>
		<div class="col-md-6">
			<dl class="users-list">
			<?php foreach( $chunk as $user ): ?>
				<dt><a href="<?=$this->url('notandi/index',array('id'=>$user->id))?>"><?=($user->name)?$user->name:'&nbsp;'?></a></dt>
				<dd><?=($user->title)?$user->title:'&nbsp;'?></dd>
				<dd><?=$user->created_date->format('Y-m-d')?></dd>
				<dd><?=$user->frequency?> innskráningar</dd>
				<dd><?=($user->is_admin)?'Kerfisstjóri':'Notandi'?></dd>
				<?php if($user->company_id):?>
					<dd><a href="<?=$this->url('fyrirtaeki/index',array('id'=>$user->company_id))?>"><?=$user->company_name?></a></dd>
				<?php else:?>
					<dd>&nbsp;</dd>
				<?php endif;?>
				<dd><?=($user->key_user)?'Formaður':'&nbsp;';?></dd>
			<?php endforeach;?>
			</dl>
		</div>
	<?php endforeach;?>
	</div>
</div>
