<?php
/** @var \Stjornvisi\Form\UserSubscriptions $form */
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
?>
<div class="panel">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__content">
					<?= $this->form()->openTag($this->form); ?>
					<div class="form-group">
						<label>Ég vil fá póst sem sendur er á:</label>
						<div class="panel panel-default">
							<div class="panel-body">
								<?php foreach ($form->getNotificationFields() as $field => $label): ?>
									<div class="checkbox">
										<label>
											<?= $this->formElement($form->get($field)); ?>
											<?= $label ?>
										</label>
									</div>
								<?php endforeach; ?>
							</div>
						</div>
					</div>

					<div class="form-group">
						<?= $this->formLabel($form->get('groups')); ?>
						<div class="checkbox">
							<?= $this->formMultiCheckbox($form->get('groups')); ?>
							<?= $this->formElementErrors($form->get('groups')); ?>
						</div>
					</div>

					<div class="form-group">
						<?= $this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default')->setValue('Uppfæra')); ?>
					</div>
					<?= $this->form()->closeTag() ?>
				</div>
			</div>
        </div>
	</div>
</div>
