
<?php
$this->form->setAttribute('class', 'form-horizontal');
?>
<div class="layout layout--three-columns">
    <section class="layout__section">
        <div class="layout__data">
            <?=$this->form()->openTag($this->form);?>
            <div class="form-group">
                <?=$this->formLabel($form->get('name'));?>
                <?=$this->formElement($form->get('name')->setAttribute('class', 'form-control'));?>
                <?=$this->formElementErrors($form->get('name'));?>
            </div>
            <div class="form-group">
                <?=$this->formLabel($form->get('email'));?>
                <?=$this->formElement($form->get('email')->setAttribute('class', 'form-control'));?>
                <?=$this->formElementErrors($form->get('email'));?>
            </div>
            <div class="form-group">
                <?=$this->formLabel($form->get('title'));?>
                <?=$this->formElement($form->get('title')->setAttribute('class', 'form-control'));?>
                <?=$this->formElementErrors($form->get('title'));?>
            </div>
            <div class="form-group">
                <?=$this->formLabel($form->get('company'));?>
                <?=$this->formElement($form->get('company')->setAttribute('class', 'form-control'));?>
                <?=$this->formElementErrors($form->get('company'));?>
            </div>
            <div class="form-group">
                <?=$this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default')->setValue('Uppfæra'));?>
            </div>
            <?= $this->form()->closeTag() ?>
            </div>
        <div class="layout__meta">&nbsp;</div>
        </section>
    <aside class="layout__aside">&nbsp;</aside>
</div>
