<?php if($this->access->is_admin || $this->access->type >= 1):?>
	<stjonvisi-control>
		<a href="<?=$this->url('vidburdir/update',array('id'=>$this->event->id));?>">Uppfæra</a>
		<a href="<?=$this->url('vidburdir/delete',array('id'=>$this->event->id));?>">Eyða</a>
		<a href="<?=$this->url('vidburdir/send-mail',array('id'=>$this->event->id,'type'=>'allir'));?>">Senda póst á meðlimi hópa</a>
		<a href="<?=$this->url('vidburdir/send-mail',array('id'=>$this->event->id, 'type'=>'gestir'));?>">Senda póst á þátttakendur</a>
		<a href="<?=$this->url('vidburdir/export-attendees',array('id'=>$this->event->id));?>">Sækja þátttakendalista (csv)</a>
		<a href="<?=$this->url('vidburdir/gallery-list',array('id'=>$this->event->id));?>">Myndalisti</a>
		<a href="<?=$this->url('vidburdir/resource-list',array('id'=>$this->event->id));?>">Ítarefni</a>
	</stjonvisi-control>
<?php endif;?>
<h2 class="layout__headline">Tengdir viðburdir</h2>
<ul class="block-list">
	<?php foreach($this->related as $event):?>
		<li class="block-item">
			<time class="block-item__time" datetime="<?=$event->event_date->format('c')?>">
				<?=$this->date($event->event_date)?>
			</time>
			<h2>
				<a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>"><?=$event->subject?></a>
			</h2>
			<ul class="block-item__tags">
				<?php foreach($event->groups as $group):?>
					<li><a href="<?=$this->url('hopur/index',array('id'=>$group->url))?>"><?=$group->name_short;?></a></li>
				<?php endforeach;?>
			</ul>
		</li>
	<?php endforeach;?>
</ul>


