ALTER TABLE User
  ADD COLUMN email_event_upcoming TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN email_global_all TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN email_group_manager TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN email_group_all TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN email_event_all TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN email_event_participant TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN email_global_manager TINYINT UNSIGNED NOT NULL DEFAULT 1,
  ADD COLUMN email_global_chairman TINYINT UNSIGNED NOT NULL DEFAULT 1;
