
<?php
	$this->headTitle( 'Stofna' );
	$this->headTitle('Viðburður');
	$this->form->setAttribute('class','form-horizontal');
?>
<div class="layout layout--three-columns">
	<section class="layout__section">

		<h1 class="layout__headline layout__headline--center">Stofna frétt</h1>

	<?=$this->form()->openTag($this->form);?>

		<div class="form-group <?=empty($this->form->get('subject')->getMessages())?'':'has-error';?>">
			<?=$this->formLabel($form->get('subject'));?>
			<?=$this->formElement($form->get('subject')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('subject'));?>
		</div>


		<div class="form-group <?=empty($this->form->get('body')->getMessages())?'':'has-error';?>">
			<?=$this->formLabel($form->get('body'));?>
			<?=$this->formElement($form->get('body')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('body'));?>
		</div>


		<div class="form-group <?=empty($this->form->get('location')->getMessages())?'':'has-error';?>">
			<?=$this->formLabel($form->get('location'));?>
			<?=$this->formElement($form->get('location')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('location'));?>
		</div>

		<div class="form-group <?=empty($this->form->get('address')->getMessages())?'':'has-error';?>">
			<?=$this->formLabel($form->get('address'));?>
			<?=$this->formElement($form->get('address')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('address'));?>
		</div>

		<div class="form-group <?=empty($this->form->get('capacity')->getMessages())?'':'has-error';?>">
			<?=$this->formLabel($form->get('capacity'));?>
			<?=$this->formElement($form->get('capacity')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('capacity'));?>
		</div>

		<div class="form-group <?=empty($this->form->get('event_date')->getMessages())?'':'has-error';?>">
			<?=$this->formLabel($form->get('event_date'));?>
			<?=$this->formElement($form->get('event_date')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('event_date'));?>
		</div>


		<div class="form-group <?=empty($this->form->get('event_time')->getMessages())?'':'has-error';?>">
			<?=$this->formLabel($form->get('event_time'));?>
			<?=$this->formElement($form->get('event_time')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('event_time'));?>
		</div>


		<div class="form-group <?=empty($this->form->get('event_end')->getMessages())?'':'has-error';?>">
			<?=$this->formLabel($form->get('event_end'));?>
			<?=$this->formElement($form->get('event_end')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('event_end'));?>
		</div>


		<div class="form-group <?=empty($this->form->get('avatar')->getMessages())?'':'has-error';?>">
			<?=$this->formLabel($form->get('avatar'));?>
			<?=$this->formElement($form->get('avatar')->setAttribute('class','form-control avatar'));?>
			<?=$this->formElementErrors($form->get('avatar'));?>
		</div>


		<div class="form-group">
			<?=$this->formLabel($form->get('groups'));?>
			<div class="checkbox">
			<?=$this->formMultiCheckbox($form->get('groups'));?>
			<?=$this->formElementErrors($form->get('groups'));?>
			</div>
		</div>

        <p>Hægt er að nota þessa vefslóð til að finna nákvæm hnit á staðsetningu: <a target="_blank" href="http://www.mapcoordinates.net/en">http://www.mapcoordinates.net/en</a></p>

        <div class="form-group <?=empty($this->form->get('latitude')->getMessages())?'':'has-error';?>">
            <?=$this->formLabel($form->get('latitude'));?>
            <?=$this->formElement($form->get('latitude')->setAttribute('class','form-control'));?>
            <?=$this->formElementErrors($form->get('latitude'));?>
        </div>

        <div class="form-group <?=empty($this->form->get('longitude')->getMessages())?'':'has-error';?>">
            <?=$this->formLabel($form->get('longitude'));?>
            <?=$this->formElement($form->get('longitude')->setAttribute('class','form-control'));?>
            <?=$this->formElementErrors($form->get('longitude'));?>
        </div>

		<div class="form-group">
			<?=$this->formElement(
				$form->get('submit')->setAttribute('class','btn btn-default')->setValue('Stofna')
			);?>
		</div>

	<?= $this->form()->closeTag() ?>

	</section>
	<aside class="layout__aside">

	</aside>
</div>
