<?php
	$this->headTitle( $this->event->subject );
	$this->headTitle('Myndalisti');
	$this->headTitle('Viðburður');
?>

<div class="layout layout--three-columns">
	<section class="layout__section">

	<h1><a href="<?=$this->url('vidburdir/index',array('id'=>$this->event->id))?>"><?=$this->event->subject?></a></h1>
	<div class="btn-group">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			Action <span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu">
			<li><a href="<?=$this->url('vidburdir/gallery-create',array('id'=>$this->event->id));?>">Bæta við mynd</a></li>
		</ul>
	</div>
	<ul>
		<?php foreach($this->gallery as $image):?>
		<li>
			<img src="<?=$this->basePath("/images/60/{$image->name}")?>" />

			<div class="btn-group">
				<button type="button" class="btn btn-default dropdown-toggle btn-xs" data-toggle="dropdown">
					Action <span class="caret"></span>
				</button>
				<ul class="dropdown-menu" role="menu">
					<li><a href="<?=$this->url('vidburdir/gallery-update',array('id'=>$image->id))?>">uppfæra</a></li>
					<li><a href="<?=$this->url('vidburdir/gallery-delete',array('id'=>$image->id))?>">eyða</a></li>
				</ul>
			</div>
		</li>
		<?php endforeach;?>
	</ul>

	</section>
	<aside class="layout__aside">

	</aside>
</div>
