<?php
$this->headTitle('Viðburðir');
?>
<div class="panel">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box box--events">
				<div class="box__title"><h2>Viðburðir á næstunni</h2></div>
				<div class="box__content">
					<? for ($i = 0; $i < 5; $i++): ?>
						<div class="entry">
							<div class="entry__title">
								<div class="entry__date">
									<span class="day">01</span>
									<span class="month">mar</span>
									<span class="year">2016</span>
								</div>
								<h3><a href="#">Harum, tempus habitasse adipisicing ornare</a></h3>
								<div class="entry__info">
									<i class="fa fa-clock-o"></i>
										08:30 - 09:45
										<span class="separator">/</span>
										<i class="fa fa-map-marker"></i> Dis ducimus dolor
								</div>
							</div>
							<div class="entry__content">
								<p>Beatae reprehenderit netus quaerat provident quam. Quam aliquip? Diamlorem recusandae, volutpat tempora accusantium ac consequatur, purus eum minus? Esse, iusto minima praesentium wisi. In taciti! Delectus veritatis interdum eget accusantium, voluptatem condimentum, corporis praesentium doloribus elementum! Sint molestiae, voluptatem! Molestiae.</p>

								<a href="#" class="btn btn-default">Hef áhuga</a> <a href="#" class="btn btn-primary">Staðfesta mætingu</a></p>
							</div>
						</div>
					<?endfor?>
				</div>
				<div class="box__footer">
					<a href="#"><i class="fa fa-plus-circle"></i> Skoða alla <?=$this->eventCount?> viðburði næsta mánuðinn</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="panel panel--inset">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box box--carousel">
				<div class="box__jip">
					<a href="<?=$this->url('vidburdir')?>" class="landing-page__headline"><i class="fa fa-plus-circle"></i> Yfirlit liðinna viðburða</a>

					<a href="#"> </a>
				</div>
				<div class="box__title"><h2>Eldri viðburðir</h2></div>
				<div class="box__content owl-carousel">
					<? for($i = 0; $i < 5; $i++) : ?>
						<div class="entry">
							<div class="entry__info">
								01.01.16
							</div>
							<div class="entry__title">
								<h3><a href="#">Nulla donec nobis cras porta</a></h3>
							</div>
							<div class="entry__image">
								<img src="//placehold.it/550x260" alt="">
							</div>
							<div class="entry__content">
								<p>Varius, hac nascetur blanditiis, nostrud officiis ut voluptatum eaque eu molestiae dolorum dolores ea, urna orci, fusce blandit architecto vehicula lorem wisi nec integer? Natus aute, numquam adipisci repellendus potenti, ullam laboris. Feugiat necessitatibus? Vestibulum irure nec leo lacinia, eaque.</p>
							</div>
						</div>
					<? endfor ?>
				</div>
			</div>
		</div>
	</div>
</div>
