
<h1>Viðburðir í <?=$this->current->format('m, Y')?></h1>
<a href="<?=$this->url('vidburdir/list',array('date'=>$this->prev->format('Y-m')))?>">prev</a> |
<a href="<?=$this->url('vidburdir/list',array('date'=>$this->next->format('Y-m')))?>">next</a>
<ul>
	<?php foreach($this->events as $event):?>
	<li>
		<a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>"><?=$event->subject?></a>
		<time>(
			<?=$event->event_date->format('Y-m-d')?> |
			<?=$event->event_time->format('H:i')?> -
			<?=$event->event_end->format('H:i')?>
		)</time>
		<ul>
			<?php if(count($event->groups)==0):?>
			<li>Stjórnvísisviðburður</li>
			<?php else:?>
			<?php foreach($event->groups as $group):?>
			<li><a href="<?=$this->url('hopur/index',array('id'=>$group->url))?>"><?=$group->name_short?></a></li>
			<?php endforeach;?>
			<?php endif;?>
		</ul>
	</li>
	<?php endforeach;?>
</ul>
