<?php
$this->headTitle('Viðburðir');
use Stjornvisi\Properties\FileProperties;
use \Stjornvisi\View\Helper\Date;
?>

<div class="panel panel--breadcrumbs">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__content">
					<a href="/">Forsíða</a>
					<span class="separator">/</span>
					Viðburðir
				</div>
			</div>
		</div>
	</div>
</div>

<div class="panel">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box box--events">
				<div class="box__title"><h2>Viðburðir á næstunni</h2></div>
				<div class="box__content">
					<? /** @var \Stjornvisi\Service\Event $event */ foreach ($this->events as $event) :?>
						<div class="entry">
							<div class="entry__title">
								<div class="entry__date">
									<span class="day"><?=$this->date($event->event_date, Date::FORMAT_DAY)?></span>
									<span class="month"><?=$this->date($event->event_date, Date::FORMAT_MONTH)?></span>
									<span class="year"><?=$this->date($event->event_date, Date::FORMAT_YEAR)?></span>
								</div>
								<h3><a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>"><?=$event->subject?></a></h3>
								<div class="entry__info">
									<i class="fa fa-clock-o"></i>
									<? if($event->event_time) : ?>
										<?=$event->event_time->format("H:i")?>
										<? if($event->event_end) : ?>
											- <?=$event->event_end->format("H:i")?>
										<? endif; ?>
									<? endif; ?>
									<? if($event->location) : ?>
										<span class="separator">/</span>
										<i class="fa fa-map-marker"></i> <?=$event->location?>
									<? endif; ?>
								</div>
							</div>
							<div class="entry__content">
								<?=$this->paragrapher(mb_substr($event->body,0,200,'utf-8').'&#8230;'  );?>
								<?php if($this->identity()): ?>
									<?php if($event->attending === false):?>
										<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>0))?>"  class="btn btn-default">Afskrá mætingu</a>
										<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>1))?>" class="btn btn-primary">Skrá mætingu</a>
									<?php elseif($event->attending == 0):?>
										<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>1))?>" class="btn btn-primary">Skrá mætingu</a>
									<?php elseif($event->attending == 1):?>
										<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>0))?>" class="btn btn-default">Afskrá mætingu</a>
									<?php endif;?>
								<?php endif;?>
							</div>
						</div>
					<?endforeach?>
				</div>
				<div class="box__footer">
					<!--
					<a href="#"><i class="fa fa-plus-circle"></i> Skoða alla <?=$this->eventCount?> viðburði næsta mánuðinn</a>
					-->
				</div>
			</div>
		</div>
	</div>
</div>

<div class="panel panel--inset">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box box--carousel">
				<div class="box__jip">
					<!--
					<a href="<?=$this->url('vidburdir')?>" class="landing-page__headline"><i class="fa fa-plus-circle"></i> Yfirlit liðinna viðburða</a>
					<a href="#"> </a>
					-->
				</div>
				<div class="box__title"><h2>Eldri viðburðir</h2></div>
				<div class="box__content owl-carousel">
					<? foreach ($this->eventsPassed as $event) : ?>
						<div class="entry">
							<div class="entry__info">
								<?=$this->date($event->event_date)?>
							</div>
							<div class="entry__title">
								<h3><a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>"><?=$event->subject?></a></h3>
							</div>
							<div class="entry__image">
								<?php if($event->avatar):?>
									<a class="block-element__poster" href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>">
										<?=$this->image($event->avatar, FileProperties::DIR_LARGE);?>
									</a>
								<?php endif;?>
							</div>
							<div class="entry__content">
								<?=$this->paragrapher(mb_substr($event->body,0,200,'utf-8').'&#8230;');?>
							</div>
						</div>
					<? endforeach; ?>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="panel" id="calendar">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__title"><h2 ><?=ucfirst($this->date($this->current,\Stjornvisi\View\Helper\Date::FORMAT_YEAR_MONTH))?></h2></div>
				<div class="box__content">
					<table class="block-calendar">
						<caption class="block-calendar__caption">
							<nav class="block-calendar__pagination">
								<a href="<?=$this->url('vidburdir/list', array('date'=>$this->prev->format('Y-m')))?>#calendar" class="prev" title="<?=$this->date($this->prev, \Stjornvisi\View\Helper\Date::FORMAT_YEAR_MONTH)?>">prev</a>
								<a href="<?=$this->url('vidburdir/list', array('date'=>$this->next->format('Y-m')))?>#calendar" class="next" title="<?=$this->date($this->next, \Stjornvisi\View\Helper\Date::FORMAT_YEAR_MONTH)?>">next</a>
							</nav>
						</caption>
						<thead class="block-calendar__header">
						<tr>
							<td>Mánudagur</td>
							<td>Þriðjudagur</td>
							<td>Miðvikudagur</td>
							<td>Fimmtudagur</td>
							<td>Föstudagur</td>
							<td>Laugardagur</td>
							<td>Sunnudagur</td>
						</tr>
						</thead>
						<tbody class="block-calendar__body">
						<?php $counter = 0;?>
						<?php foreach ($this->calendar as $key => $column): ?>
							<?php if( $counter % 7 == 0 ):?>
								<tr>
							<?php endif;?>
							<td>
								<span class="block-calendar__date-label"><?=substr($key, 8, 2)?></span>
								<ul class="block-calendar__subject-list">
									<?php if( !empty($column)):?>
										<?php foreach($column as $event):?>
											<li>
												<a href="<?=$this->url('vidburdir/index', array('id'=>$event->id))?>"><?=$event->subject;?></a>
												<ul class="block-calendar__group-list">
													<?php if(count($event->groups)==0):?>
														<li>Stjórnvísisviðburður</li>
													<?php else:?>
														<?php foreach($event->groups as $group):?>
															<li><a href="<?=$this->url('hopur/index', array('id'=>$group->url))?>"><?=$group->name_short?></a></li>
														<?php endforeach;?>
													<?php endif;?>
												</ul>
											</li>
										<?php endforeach;?>
									<?php else:?>
										<li>&nbsp;</li>
									<?php endif;?>
								</ul>
							</td>
							<?php if( $counter % 7 == 6 ):?>
								</tr>
							<?php endif;?>

							<?php $counter++?>
						<?php endforeach; ?>
						</tbody>
						<tfoot class="block-calendar__footer">

						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
