<?php
$this->headTitle( $this->event->subject );
$this->headTitle('Skráarlisti - Stofna');
$this->headTitle('Viðburður');
$this->form->setAttribute('class','form-horizontal');
?>
<div class="layout layout--three-columns">
	<section class="layout__section">
		<h1 class="layout__headline layout__headline--center">
			Ítarefni fyrir :<a href="<?=$this->url('vidburdir/index',array('id'=>$this->event->id))?>"><?=$this->event->subject;?></a>
		</h1>
		<?=$this->form()->openTag($this->form);?>

		<div class="form-group">
			<?=$this->formLabel($form->get('name'));?>
			<?=$this->formElement($form->get('name')->setAttribute('class','form-control media'));?>
			<?=$this->formElementErrors($form->get('name'));?>
		</div>


		<div class="form-group">
			<?=$this->formLabel($form->get('description'));?>
			<?=$this->formElement($form->get('description')->setAttribute('class','form-control'));?>
			<?=$this->formElementErrors($form->get('description'));?>
		</div>

		<div class="form-group">
			<?=$this->formElement(
				$form->get('submit')->setAttribute('class','btn btn-default')->setValue('Stofna')
			);?>
		</div>

		<?= $this->form()->closeTag() ?>
	</section>
	<aside class="layout__aside">

	</aside>
</div>


