<?php
use Stjornvisi\Properties\FileProperties;

$this->headTitle($this->event->subject);
$this->headTitle('Skráarlisti');
$this->headTitle('Viðburður');
?>

<div class="panel">
    <div class="panel__container">
        <div class="panel__content">
            <div class="box">
                <div class="box__title">
                    <h1>
                        <a href="<?= $this->url('vidburdir/index', ['id' => $this->event->id]) ?>">Ítarefni
                            fyrir <?= $this->event->subject ?></a>
                    </h1>
                </div>
                <div class="box__content">
                    <a href="<?= $this->url('vidburdir/resource-create', ['id' => $this->event->id]); ?>"
                       class="btn btn-default">Bæta við ítarefni</a>

                    <ul class="block-supplement resource-list">
                        <?php foreach ($this->resources as $resource): ?>
                            <li>
                                <a href="<?= $this->basePath(implode('/', [FileProperties::DIR_IMAGES, FileProperties::DIR_RAW, $resource->name])) ?>"
                                   target="_blank"><?= $resource->name ?></a>
                                <stjonvisi-control class="inline">
                                    <a href="<?= $this->url('vidburdir/resource-update', ['id' => $resource->id]) ?>"
                                       class="update"><i class="icon-check"></i> uppfæra</a>
                                    <a href="<?= $this->url('vidburdir/resource-delete', ['id' => $resource->id]) ?>"
                                       class="delete"><i class="icon-close"></i> eyða</a>
                                </stjonvisi-control>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


