<?php $this->form->setAttribute('class','form-horizontal');?>
<div class="layout layout--three-columns">
	<section class="layout__section">

		<?=$this->form()->openTag($this->form);?>

		<div class="">
			<div class="">
				<div class="form-group">
					<?=$this->formLabel($form->get('subject'));?>
					<?=$this->formElement($form->get('subject')->setAttribute('class','form-control'));?>
					<?=$this->formElementErrors($form->get('subject'));?>
				</div>
				<div class="form-group">
					<?=$this->formLabel($form->get('body'));?>
					<?=$this->formElement($form->get('body')->setAttribute('class','form-control')->setAttribute('rows','25'));?>
					<?=$this->formElementErrors($form->get('body'));?>
				</div>
				<div class="form-group">
					<?=$this->formLabel($form->get('location'));?>
					<?=$this->formElement($form->get('location')->setAttribute('class','form-control'));?>
					<?=$this->formElementErrors($form->get('location'));?>
				</div>

				<div class="form-group">
					<?=$this->formLabel($form->get('address'));?>
					<?=$this->formElement($form->get('address')->setAttribute('class','form-control'));?>
					<?=$this->formElementErrors($form->get('address'));?>
				</div>
				<div class="form-group">
					<?=$this->formLabel($form->get('capacity'));?>
					<?=$this->formElement($form->get('capacity')->setAttribute('class','form-control'));?>
					<?=$this->formElementErrors($form->get('capacity'));?>
				</div>
			</div>
			<div class="">

				<div class="row third">
					<div class="column">
						<div class="form-group">
							<?=$this->formLabel($form->get('event_date'));?>
							<?=$this->formElement($form->get('event_date')->setAttribute('class','form-control'));?>
							<?=$this->formElementErrors($form->get('event_date'));?>
						</div>
					</div>
					<div class="column">
						<div class="form-group">
							<?=$this->formLabel($form->get('event_time'));?>
							<?=$this->formTime($form->get('event_time')->setAttribute('class','form-control'));?>
							<?=$this->formElementErrors($form->get('event_time'));?>
						</div>
					</div>
					<div class="column">
						<div class="form-group">
							<?=$this->formLabel($form->get('event_end'));?>
							<?=$this->formTime($form->get('event_end')->setAttribute('class','form-control'));?>
							<?=$this->formElementErrors($form->get('event_end'));?>
						</div>
					</div>
				</div>

				<div class="form-group">
					<?=$this->formLabel($form->get('avatar'));?>
					<?=$this->formElement($form->get('avatar')->setAttribute('class','form-control avatar'));?>
					<?=$this->formElementErrors($form->get('avatar'));?>
				</div>


				<div class="form-group">
					<?=$this->formLabel($form->get('groups'));?>
					<div class="checkbox">
					<?=$this->formMultiCheckbox($form->get('groups'));?>
					<?=$this->formElementErrors($form->get('groups'));?>
					</div>
				</div>
			</div>
		</div>

		<div class="">
			<?=$this->formElement($form->get('submit')->setAttribute('class','btn btn-default'));?>
			<a href="#" class="btn cancel">Cancel</a>
		</div>

		<?= $this->form()->closeTag() ?>

	</section>
	<aside class="layout__aside">

	</aside>
</div>
