<?php
$this->form->setAttribute('class','form-horizontal');
?>
<?=$this->form()->openTag($this->form);?>

	<div class="form-group">
		<?=$this->formLabel($form->get('title'));?>
		<?=$this->formElement($form->get('title')->setAttribute('class','form-control'));?>
		<?=$this->formElementErrors($form->get('title'));?>
	</div>
	<div class="form-group">
		<?=$this->formLabel($form->get('body'));?>
		<?=$this->formElement($form->get('body')->setAttribute('class','form-control'));?>
		<?=$this->formElementErrors($form->get('body'));?>
	</div>
	<div class="form-group">
		<?=$this->formLabel($form->get('avatar'));?>
		<?=$this->formElement($form->get('avatar')->setAttribute('class','form-control avatar'));?>
		<?=$this->formElementErrors($form->get('avatar'));?>
	</div>
	<div class="form-group">
		<?=$this->formElement($form->get('submit')->setAttribute('class','btn btn-default'));?>
	</div>
<?= $this->form()->closeTag() ?>
