<?php
$this->form->setAttribute('class','form-horizontal');
?>
<div class="layout layout--three-columns">
    <section class="layout__section">
        <?php if( isset($this->group->name_short) ):?>
            <h1>Uppfæra <a href="<?=$this->url('hopur/index', array('id'=>$this->group->url))?>"><?=$this->group->name_short?></a> frétt</h1>
        <?php else:?>
            <h1>Uppfæra Stjónvísisfrétt</h1>
        <?php endif;?>

    <?=$this->form()->openTag($this->form);?>

    <div class="form-group">
        <?=$this->formLabel($form->get('title'));?>
        <?=$this->formElement($form->get('title')->setAttribute('class', 'form-control'));?>
        <?=$this->formElementErrors($form->get('title'));?>
    </div>
    <div class="form-group">
        <?=$this->formLabel($form->get('body'));?>
        <?=$this->formElement($form->get('body')->setAttribute('class', 'form-control'));?>
        <?=$this->formElementErrors($form->get('body'));?>
    </div>
    <div class="form-group">
        <?=$this->formLabel($form->get('avatar'));?>
        <?=$this->formElement($form->get('avatar')->setAttribute('class', 'form-control avatar'));?>
        <?=$this->formElementErrors($form->get('avatar'));?>
    </div>
    <div class="form-group">
        <?=$this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default')->setValue('Uppfæra'));?>
    </div>
    <?= $this->form()->closeTag() ?>
        </section>
    <aside class="layout__aside"></aside>
</div>
