<?php
/**
 * Created by PhpStorm.
 * User: einar
 * Date: 07/11/14
 * Time: 14:32
 */

?>

<div class="panel panel--columns-two">
	<div class="panel__container">
		<div class="panel__content">
			<ul class="stepper">
				<li class="stepper--done">1# Notendaupplýsingar</li>
				<li class="stepper--done">2# Fyrirtækjaupplýsingar</li>
				<li class="stepper--current">3# Innskráning</li>
			</ul>
			<div class="box">
				<div class="box__content">
					<h2>Facebook</h2>
					<p>Facebook auðkenni er æskileg leið.</p>
					<a href="<?=$this->url('access/confirm');?>?facebook=1" class="btn btn-facebook js-btn-facebook"><i class="fa fa-facebook"></i> | Auðkenna með Facebook</a>

					<h3 class="layout__sepline">eða</h3>
					<h2 class="layout__headline">Notendanafn / lykilorð</h2>
					<p>Þú getur líka valið að nota hefðbundið lykilorð.
						Þá þurfum við að fá frá þér lykilorð.</p>
					<?=$this->form()->openTag($this->form);?>
						<div class="form-group">
							<?=$this->formLabel($this->form->get('name'));?>
							<?=$this->formElement($this->form->get('name')->setAttribute('class', 'form-control'));?>
							<?=$this->formElementErrors($this->form->get('name'));?>
						</div>
						<div class="form-group">
							<?=$this->formLabel($this->form->get('password'));?>
							<?=$this->formElement($this->form->get('password')->setAttribute('class', 'form-control'));?>
							<?=$this->formElementErrors($this->form->get('password'));?>
						</div>
						<div class="form-group">
							<?=$this->formLabel($this->form->get('password-again'));?>
							<?=$this->formElement($this->form->get('password-again')->setAttribute('class', 'form-control'));?>
							<?=$this->formElementErrors($this->form->get('password-again'));?>
						</div>
						<div class="form-group">
							<?=$this->formElement(
								$this->form->get('submit')->setAttribute('class', 'btn btn-default')->setValue('Stofna')
							);?>
						</div>

					<?= $this->form()->closeTag() ?>
				</div>
			</div>
			<div class="box">
				<div class="box__content">
					<section class="user-create__help-section user-create__help-section--active js-help-select">
					<h3 class="layout__headline">Facebook eða lykilorð</h3>
					<p>Stjónvísi býður nú notendum sínum upp á að nota Facebook
						sem auðkenni.</p>
						<p>Hefðbundin notendanafn/lykilorð leið er líka í boði.</p>
					</section>

					<section class="user-create__help-section js-facebook-select">
						<h3 class="layout__headline">Facebook</h3>
						<p>Facebook auðkenni er um margt betri leið en að nota
							hefðbundið lykilorð. Notandi þarf hvortki að muna notendanafnið
							sitt né lykilorð.</p>
						<p>Stjónvísi mælir með þessari aðferð.</p>
					</section>

					<section class="user-create__help-section js-password-select">
					<h3 class="layout__headline">Lykilorð</h3>
					<p>Þeir notendur sem af einhverjum ástæðum vilja ekki nota Facebook
						auðkenni geta valið sér lykilorð til auðkennis</p>
					</section>
				</div>
			</div>
		</div>
    </div>
</div>

<script>
    var helpers = document.querySelectorAll('.user-create__help-section');
    document.querySelector('.js-facebook-select').addEventListener('click',function(event){
        event.preventDefault();
        Array.prototype.forEach.call(helpers,function(text){
            text.classList.remove('user-create__help-section--active');
        });
        this.classList.add('user-create__help-section--active');
        document.querySelector('.js-btn-facebook').focus();
    },false);

    document.querySelector('.js-password-select').addEventListener('click',function(event){
        event.preventDefault();
        Array.prototype.forEach.call(helpers,function(text){
            text.classList.remove('user-create__help-section--active');
        });
        this.classList.add('user-create__help-section--active');
        document.querySelector('.js-input-passwd').focus();
    },false);

    document.querySelector('.js-help-select').addEventListener('click',function(event){
        event.preventDefault();
        Array.prototype.forEach.call(helpers,function(text){
            text.classList.remove('user-create__help-section--active');
        });
        this.classList.add('user-create__help-section--active');
    },false);
</script>

