<?php
/**
 * Created by PhpStorm.
 * User: einar
 * Date: 07/11/14
 * Time: 08:45
 */
?>

<div class="panel panel--columns-two">
    <div class="panel__container">
		<div class="panel__content">
			<ul class="stepper">
				<li class="stepper--done">1# Notendaupplýsingar</li>
				<li class="stepper--current">2# Fyrirtækjaupplýsingar</li>
				<li>3# Innskráning</li>
			</ul>
			<div class="box">
				<div class="widget-slider company-connect">
					<div class="widget-slider__wrapper" style="margin-left: -<?=$this->panel*100?>%">
						<div class="widget-slider__slide">
							<h2 class="layout__headline">Hvað passar best við þig?</h2>
							<ul class="block-simple-list">
								<li class=""><a href="#" data-slide="1"><i class="fa fa-chevron-right"></i> Ég er starfsmaður fyrirtækis</a></li>
								<li class=""><a href="#" data-slide="2"><i class="fa fa-chevron-right"></i> Ég er háskólanemi</a></li>
								<li class=""><a href="#" data-slide="3"><i class="fa fa-chevron-right"></i> Ég er einstaklingur</a></li>
							</ul>
						</div>
						<div class="widget-slider__slide">
							<div>
								<a href="#" data-slide="0" class="company-connect__back-button"><i class="fa fa-chevron-left"></i></a>
								<?=$this->form()->openTag($this->companySelectForm);?>
								<h2 class="layout__headline">Ég er starfsmaður fyrirtækis</h2>
								<p class="layout__sub-paragraph">Veldu fyrirtæki úr fellilistanum</p>
								<div class="form-group">
									<?=$this->formLabel($this->companySelectForm->get('company-select'));?>
									<?=$this->formElement($this->companySelectForm->get('company-select')->setAttribute('class', 'form-control'));?>
									<?=$this->formElementErrors($this->companySelectForm->get('company-select'));?>
								</div>
								<div class="form-group form-group--right">
									<?=$this->formElement(
										$this->companySelectForm->get('submit-company-select')->setAttribute('class', 'btn btn-default')->setValue('Áfram')
									);?>
								</div>
								<?= $this->form()->closeTag() ?>
							</div>
							<h3 class="layout__sepline">eða</h3>
							<div>
								<?=$this->form()->openTag($this->companyForm);?>
								<h2 class="layout__headline">Ég er starfsmaður fyrirtækis, en fyrirtækið er ekki á skrá</h2>

								<div class="poof__toggle">
									<a href="#" class="btn btn-info poof__button">Skrá upplýsingar um fyrirtækið</i></a>
								</div>
								<div class="poof__content">
									<div class="form-group">
										<?=$this->formLabel($this->companyForm->get('company-name'));?>
										<?=$this->formElement($this->companyForm->get('company-name')->setAttribute('class', 'form-control'));?>
										<?=$this->formElementErrors($this->companyForm->get('company-name'));?>
									</div>
									<div class="form-group <?=(!empty($this->companyForm->get('company-ssn')->getMessages()))?'has-error':'';?> ">
										<?=$this->formLabel($this->companyForm->get('company-ssn'));?>
										<?=$this->formElement($this->companyForm->get('company-ssn')->setAttribute('class', 'form-control'));?>
										<?=$this->formElementErrors($this->companyForm->get('company-ssn'));?>
									</div>
									<div class="form-group">
										<?=$this->formLabel($this->companyForm->get('company-address'));?>
										<?=$this->formElement($this->companyForm->get('company-address')->setAttribute('class', 'form-control'));?>
										<?=$this->formElementErrors($this->companyForm->get('company-address'));?>
									</div>
									<div class="form-group">
										<?=$this->formLabel($this->companyForm->get('company-zip'));?>
										<?=$this->formElement($this->companyForm->get('company-zip')->setAttribute('class', 'form-control'));?>
										<?=$this->formElementErrors($this->companyForm->get('company-zip'));?>
									</div>
									<div class="form-group">
										<?=$this->formLabel($this->companyForm->get('company-web'));?>
										<?=$this->formElement($this->companyForm->get('company-web')->setAttribute('class', 'form-control'));?>
										<?=$this->formElementErrors($this->companyForm->get('company-web'));?>
									</div>
									<div class="form-group">
										<?=$this->formLabel($this->companyForm->get('company-size'));?>
										<?=$this->formElement($this->companyForm->get('company-size')->setAttribute('class', 'form-control'));?>
										<?=$this->formElementErrors($this->companyForm->get('company-size'));?>
									</div>
									<div class="form-group">
										<?=$this->formLabel($this->companyForm->get('company-type'));?>
										<?=$this->formElement($this->companyForm->get('company-type')->setAttribute('class','form-control'));?>
										<?=$this->formElementErrors($this->companyForm->get('company-type'));?>
									</div>
									<div class="form-group form-group--right">
										<?=$this->formElement(
											$this->companyForm->get('submit-company-create')->setAttribute('class', 'btn btn-default')->setValue('Stofna fyrirtæki')
										);?>
									</div>
								</div>
								<?= $this->form()->closeTag() ?>
							</div>
						</div>
						<div class="widget-slider__slide">
							<a href="#" data-slide="0" class="company-connect__back-button"><i class="fa fa-chevron-left"></i></a>
							<?=$this->form()->openTag($this->universitySelectForm);?>
							<h2 class="layout__headline">Ég er háskólanemi</h2>
							<p>Vinsamlegast veldu skóla hér</p>
							<div class="form-group">
								<?=$this->formLabel($this->universitySelectForm->get('university-select'));?>
								<?=$this->formElement($this->universitySelectForm->get('university-select')->setAttribute('class', 'form-control'));?>
								<?=$this->formElementErrors($this->universitySelectForm->get('university-select'));?>
							</div>
							<div class="form-group form-group--right">
								<?=$this->formElement(
									$this->universitySelectForm->get('submit-university-select')->setAttribute('class', 'btn btn-default')->setValue('Velja')
								);?>
							</div>
							<?= $this->form()->closeTag() ?>

						</div>
						<div class="widget-slider__slide">
							<a href="#" data-slide="0" class="company-connect__back-button"><i class="fa fa-chevron-left"></i></a>
							<?=$this->form()->openTag($this->individualForm);?>
							<h2 class="layout__headline">Ég er einstaklingur</h2>
							<p>Þá þarf ég að fá hjá þér kennitölu og heimilsfang</p>
							<div class="form-group <?=(!empty($this->individualForm->get('person-ssn')->getMessages()))?'has-error':'';?> ">
								<?=$this->formLabel($this->individualForm->get('person-ssn'));?>
								<?=$this->formElement($this->individualForm->get('person-ssn')->setAttribute('class', 'form-control'));?>
								<?=$this->formElementErrors($this->individualForm->get('person-ssn'));?>
							</div>
							<div class="form-group">
								<?=$this->formLabel($this->individualForm->get('person-address'));?>
								<?=$this->formElement($this->individualForm->get('person-address')->setAttribute('class', 'form-control'));?>
								<?=$this->formElementErrors($this->individualForm->get('person-address'));?>
							</div>
							<div class="form-group">
								<?=$this->formLabel($this->individualForm->get('person-zip'));?>
								<?=$this->formElement($this->individualForm->get('person-zip')->setAttribute('class', 'form-control'));?>
								<?=$this->formElementErrors($this->individualForm->get('person-zip'));?>
							</div>
							<div class="form-group form-group--right">
								<?=$this->formElement(
									$this->individualForm->get('submit-individual')->setAttribute('class', 'btn btn-default')->setValue('Stofna')
								);?>
							</div>
							<?= $this->form()->closeTag() ?>
						</div>
					</div>
				</div>

			</div>
			<div class="box">
				<div class="box__title"><h2>Hvað er þetta?</h2></div>
				<div class="box__content">
					<section class="user-create__help-section <?=($this->panel==0)?'user-create__help-section--active':'';?>" data-slide="0">
						<h3 class="layout__headline">Fyrirtækjaupplýsingar</h3>
						<p>Allir notendur verða að vera tengdir fyrirtæki eða stofnun.</p>
						<p>Þú þarft að velja hér til vinstri hvaða fyrirtæki eða stofnun
							þú vilt tengjast.</p>
						<p><strong>Þú velur aðeins einn af þremur neðangreindum möguleikum</strong></p>
					</section>
					<section class="user-create__help-section <?=($this->panel==1)?'user-create__help-section--active':'';?>" data-slide="1">
						<h4 class="layout__headline">1. Starfsmaður fyrirtækis</h4>
						<p>Ef þú ert starfsmaður fyrirtækis, þá velur þú það hér. Það getur verið
							að fyrirtækið sé ekki á skrá, ef svo er þá stofnar þú það í leiðinni</p>
					</section>
					<section class="user-create__help-section <?=($this->panel==2)?'user-create__help-section--active':'';?>" data-slide="2">
						<h4 class="layout__headline">2. Háskólanemi</h4>
						<p>Stjónvísi hefur innan sinna vébanda flesta háskóla landsins. Ef þú ert
							háskólanemi getur þú valið það hér.</p>
					</section>
					<section class="user-create__help-section <?=($this->panel==3)?'user-create__help-section--active':'';?>" data-slide="3">
						<h4 class="layout__headline">3. Einstaklingur</h4>
						<p>Sértu einstaklingur sem langar að taka þátt í starfsemi Stjónvísi
							þá velur þú það hér.</p>
					</section>
				</div>
			</div>
		</div>
    </div>
</div>

<script>
    var slideDesc = document.querySelector('.company-connect .widget-slider__wrapper');
    var helpers = document.querySelectorAll('.user-create__help-section');
    Array.prototype.forEach.call(document.querySelectorAll('[data-slide]'),function(i,index){
        i.addEventListener('click',function(event){
            event.preventDefault();
            slideDesc.style.marginLeft = ("-" + (this.getAttribute('data-slide')*100) + "%");
            Array.prototype.forEach.call(helpers,function(text){
                text.classList.remove('user-create__help-section--active');
            });
            helpers[this.getAttribute('data-slide')].classList.add('user-create__help-section--active')

        },false);
    });
</script>
