<?php $this->form->setAttribute('class','form-horizontal'); ?>

<div class="layout layout--three-columns page-login">
	<section class="layout__section">
		<div class="layout__data page-login__service">
			<p>Stjónvísi býður nú upp á að notendur noti Facebook sem auðkenni. Auðvelt er
				að tengja eldri notendareikninga við þessa þjónustu, prufaðu bara.</p>
			<a href="<?=$this->facebook( \Stjornvisi\Controller\AuthController::LOGIN_CALLBACK_FACEBOOK );?>" class="btn btn-primary btn-facebook"><i class="icon-facebook"></i>| Facebook innskráning</a>

			<a href="" class="btn btn-success">Stofna aðgang</a>
		</div>
		<div class="layout__meta page-login__manual">
			<p>Að sjálfsögðu er hægt að skrá sig inn með gamla mátanum</p>
			<?=$this->form()->openTag($this->form);?>

			<div class="form-group">
				<?=$this->formLabel($this->form->get('email'));?>
				<?=$this->formElement($this->form->get('email')->setAttribute('class','form-control'));?>
				<?=$this->formElementErrors($this->form->get('email'));?>
			</div>
			<div class="form-group">
				<?=$this->formLabel($this->form->get('passwd'));?>
				<?=$this->formElement($this->form->get('passwd')->setAttribute('class','form-control'));?>
				<?=$this->formElementErrors($this->form->get('passwd'));?>
			</div>

			<div class="form-group">
				<?=$this->formElement($this->form->get('submit')->setAttribute('class','btn btn-default'));?>
			</div>

			<?= $this->form()->closeTag() ?>
		</div>

	</section>
	<aside class="layout__aside"></aside>
</div>



<?php print_r($this->form->getMessages(),true)?>

<!--a href="#" class="btn brn-default">facebbok</a>
<a href="#" class="btn brn-default">linkedIn</a>
<a href="#" class="btn brn-default">g+</a-->