<div class="panel">
    <div class="panel__container">
        <div class="panel__content">
            <div class="box">
                <div class="box__title"><h1>Týnt lykilorð</h1></div>
                <div class="box__content">
                <?php if($this->message):?>
                <p><?=$this->message;?></p>
            <?php else:?>
                <?=$this->form()->openTag($this->form);?>

                <div class="form-group">
                    <?=$this->formLabel($form->get('email'));?>
                    <?=$this->formElement($form->get('email')->setAttribute('class', 'form-control'));?>
                    <?=$this->formElementErrors($form->get('email'));?>
                </div>

                <div class="form-group">
                    <?=$this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default'));?>
                </div>
                <?= $this->form()->closeTag() ?>
            <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</div>




