<div class="layout layout--three-columns page-company">
    <section class="layout__section">
        <div class="layout__data">
            <h1 class="layout__headline">Týnd lykilorð</h1>
            <?php if($this->message):?>
                <p><?=$this->message;?></p>
            <?php else:?>
                <?php
                $this->form->setAttribute('class', 'form-horizontal');
                ?>
                <?=$this->form()->openTag($this->form);?>

                <div class="form-group">
                    <?=$this->formLabel($form->get('email'));?>
                    <?=$this->formElement($form->get('email')->setAttribute('class', 'form-control'));?>
                    <?=$this->formElementErrors($form->get('email'));?>
                </div>

                <div class="form-group">
                    <?=$this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default'));?>
                </div>
                <?= $this->form()->closeTag() ?>
            <?php endif;?>
        </div>
        <div class="layout__meta"></div>
    </section>
    <aside class="layout__aside"></aside>
</div>




