<?php
/**
 * Created by PhpStorm.
 * User: einar
 * Date: 31/10/14
 * Time: 15:44
 */

?>
<div class="layout layout--three-columns">
    <section class="layout__section">
        <div class="page-group__header">
            <?php if( $this->user ):?>
                <h1 class="layout__headline">Póstur hefur verið sendur</h1>
                <p>Til þess að ganga úr skugga um að þú sért réttur handhafi netfangsins
                    hefur tölvupóstur verið sendur á tilgreint netfang. Í honum er slóð
                    sem þú þarft að fylgja til að klára skráningu.</p>
            <?php else:?>
                <h1 class="layout__headline">Netfang ekki á skrá</h1>
                <p>Netfang er ekki á skrá.</p>
            <?php endif;?>
        </div>
    </section>
    <aside class="layout__aside"></aside>
</div>



