<?if($this->admin):?>
<div class="panel panel--admin">
	<div class="panel__container">
		<div class="panel__content">
			<a href="<?=$this->url('page/update', array('id'=>$this->page->id))?>"><i class="fa fa-check"></i> Uppfæra</a>
		</div>
	</div>
</div>
<?endif?>

<div class="panel">
    <div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__content">
					<?=$this->paragrapher($this->page->body)?>
				</div>
			</div>
		</div>
    </div>
</div>

