<?php $this->form->setAttribute('class','form-horizontal'); ?>
<div class="panel">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__content">
					<?=$this->form()->openTag($this->form);?>

					<div class="form-group">
						<?=$this->formLabel($form->get('label'));?>
						<?=$this->formElement($form->get('label')->setAttribute('class', 'form-control'));?>
						<?=$this->formElementErrors($form->get('label'));?>
					</div>
					<div class="form-group">
						<?=$this->formLabel($form->get('body'));?>
						<?=$this->formElement($form->get('body')->setAttribute('class', 'form-control'));?>
						<?=$this->formElementErrors($form->get('body'));?>
					</div>
					<div class="form-group">
						<?=$this->formElement($form->get('submit')->setAttribute('class', 'btn btn-default')->setValue('Uppfæra'));?>
					</div>
					<?= $this->form()->closeTag() ?>
				</div>
			</div>
		</div>
	</div>
</div>
