<?php if($this->identity):?>

	<div>
		<section>
			<div>
				<h1>Viðburðir</h1>
				<ul>
				<?php foreach( $this->events as $event ):?>
					<li>
						<article class="block-element">
							<header class="block-element__header">
								<time class="block-element__time"><?=$event->event_date->format('Y-m-d');?> | <?=$event->event_time->format('H:m');?> - <?=$event->event_end->format('H:m');?></time>
								<h1><a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>"><?=$event->subject?></a></h1>
							</header>
							<section class="block-element__body">
								<?php if($event->avatar):?>
								<a class="block-element__poster" href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>">
									<img src="<?=$this->basePath("/images/300/{$event->avatar}")?>" alt="mynd með viðburði" />
								</a>
								<?php endif;?>
								<?=$this->paragrapher( mb_substr($event->body,0,350,'utf-8').'&#8230;'  );?>
							</section>
							<aside class="block-element__aside">
								<ul class="block-element__tags">
									<?php if( count($event->groups) == 0 ):?>
										<li><span>Stjónvísisviðburður</span></li>
									<?php else:?>
										<?php foreach($event->groups as $group):?>
											<li><a href="/hopur/<?=$group->url;?>"><?=$group->name_short;?></a></li>
										<?php endforeach;?>
									<?php endif; ?>
								</ul>
							</aside>
							<footer class="block-element__footer">
								<?php if($event->attending === null):?>
									<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>1))?>" class="attending yes" title="Skrá mætingu">mæti</a>
									<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>0))?>" class="attending no" title="Afskrá mætingu">mæti ekki</a>
								<?php elseif($event->attending == 0):?>
									<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>1))?>" class="attending yes" title="Skrá mætingu">mæti</a>
									<span class="attending no" title="Afkrá mætingu">mæti ekki</span>
								<?php elseif($event->attending == 1):?>
									<span class="attending yes" title="Skrá mætingu">mæti</span>
									<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>0))?>" class="attending no" title="Afskrá mætingu">mæti ekki</a>
								<?php endif;?>
							</footer>
						</article>
					</li>
				<?php endforeach;?>
			</ul>
			</div>

			<div>
				<h1>Fréttir</h1>
				<ul>
				<?php foreach( $this->news as $news ):?>
					<li>
						<article class="block-element">
							<header class="block-element__header">
								<time class="block-element__time"><?=$news->created_date?></time>
								<h1><a href="<?=$this->url('frettir/index',array('id'=>$news->id))?>"><?=$news->title?></a></h1>
							</header>
							<section class="block-element__body">
								<?php if($news->avatar):?>
								<a href="<?=$this->url('frettir/index',array('id'=>$news->id))?>" class="block-element__poster">
									<img src="<?=$this->basePath("/images/300/{$news->avatar}")?>" alt="mynd með frétt" />
								</a>
								<?php endif;?>
								<?=$this->paragrapher( mb_substr($news->body,0,350,'utf-8').'&#8230;'  );?>
							</section>
							<aside class="block-element__aside">
								<ul class="block-element__tags">
									<li>
										<?php if( $news->group_id ):?>
										<a href="<?=$this->url('hopur/index',array('id' => $news->group->url))?>"><?=$news->group->name_short?></a>
										<?php else:?>
										<span>Stjórnvísi</span>
										<?php endif;?>
									</li>
								</ul>
							</aside>
							<footer></footer>
						</article>
					</li>
				<?php endforeach;?>
			</ul>
			</div>
		</section>
		<aside>
			<h1>Fylgiskrár</h1>
			<ul>
				<?php foreach( $this->media as $media ):?>
					<li>
						<a href="/image/original/<?=$media->name?>" title="<?=$media->name?>"><?=$media->name?></a>
						<!--a href="<?=$this->url('vidburdir/index',array('id'=>$media->event->id))?>"><?=$media->event->subject?></a-->
					</li>
				<?php endforeach;?>
			</ul>
		</aside>
	</div>

<?php else:?>
<div class="landing-page">
	<div class="hero">
		<img src="<?=$this->basePath("/frontpage/logo-frontpage.png")?>"  />
		<h4>Félag um framsækna stjórnun</h4>
		<h1>Stjórnvísi er stærsta stjórnunarfélag á Íslandi
			með 2.150 virka félagsmenn og yfir 300 fyrirtæki innan sinna raða.</h1>
	</div>
	<div class="login-buttons">
		<a href="<?=$this->facebook( \Stjornvisi\Controller\AuthController::LOGIN_CALLBACK_FACEBOOK );?>" class="btn btn-primary btn-facebook"><i class="icon-facebook"></i>Facebook innskráning</a>
		<!--a href="<?=$this->url('auth',['type'=>'facebook'])?>" class="btn btn-default">Innskráning</a-->
		<a href="" class="btn btn-success">Stofna aðgang</a>
	</div>

	<div class="about">
		<div>
			<h1>Stjórnvísi er opið öllum einstaklingum, fyrirtækjum og stofnunum sem hafa áhuga á stjórnun;
			stjórnendum, sérfræðingum, nemendum og öðrum áhugamönnum um stjórnun.</h1>
			<p>Stjórnvísi býður hagstæðustu símenntunina um stjórnun á markaðnum.  Stjórnvísi er með kjarnastarf
			sitt í kraftmiklum faghópum félagsmanna en jafnframt stendur félagið fyrir almennum ráðstefnum, viðburðum
			og verðlaunum um stjórnun.</p>
			<a href="<?=$this->url('um')?>" class="btn btn-success btn-green">Kynntu þér starfssemi Stjórnvísi</a>
		</div>
	</div>

	<div class="groups">
		<div class="text">
			<h1>Stjórnvísi er áhugamannafélag í eigu félagsmanna og starfar ekki með fjárhagslegan ágóða í huga.</h1>
			<p>Stjórnvísi er með kjarastarf sitt í kraftmiklum faghópum félagsmanna en jafnframt stendur félagið
			fyrir almennum ráðstefnum, viðburðum og verðlaunaveitingum í stjórnun.</p>
			<a href="<?=$this->url('hopur')?>" class="btn btn-success btn-green">Kynntu þér faghópa innan Stjórnvísi</a>
		</div>
	</div>


	<div class="events-panel">
		<h1>Viðburðir</h1>
		<?php if($this->event) : ?>
			<article>
				<aside>
					<?php if($this->event->avatar):?>
					<img src="<?=$this->basePath("/images/300-square/{$this->event->avatar}")?>" />
					<?php endif;?>
				</aside>
				<header>
					<h2><a href="<?=$this->url('vidburdir/index',array('id'=>$this->event->id))?>"><?=$this->event->subject?></a></h2>
					<time>
						<?=($this->event->event_date)?$this->event->event_date->format('Y-m-d'):''?> |
						<?=($this->event->event_time)?$this->event->event_time->format('H:i'):''?> -
						<?=($this->event->event_end)?$this->event->event_end->format('H:i'):''?>
					</time>
				</header>
				<section>
					<?=$this->paragrapher(mb_substr($this->event->body,0,600,'utf-8'));?>
				</section>
				<footer>
					<ul>
						<?php foreach($this->event->groups as $group):?>
							<li><a href="<?=$this->url('hopur/index',array('id'=>$group->url))?>"><?=$group->name_short?></a></li>
						<?php endforeach;?>
					</ul>
				</footer>
			</article>
		<?php else : ?>
			<h1>Engir viðburðir skráðir</h1>
		<?php endif; ?>
		<div>
			<a href="<?=$this->url('vidburdir')?>" class="btn btn-default">Allir viðburðir</a>
		</div>

	</div>


	<div class="news-panel">
		<h1>Fréttir</h1>
		<article>
			<aside>
				<?php if($this->news->avatar):?>
				<img src="<?=$this->basePath("/images/300-square/{$this->news->avatar}")?>" />
				<?php endif;?>
			</aside>
			<header>
				<h2><a href="<?=$this->url('frettir/index',array('id'=>$this->news->id))?>"><?=$this->news->title?></a></h2>
				<time><?=$this->news->created_date->format('d. M Y')?></time>
			</header>
			<section>
				<?=$this->paragrapher(mb_substr($this->news->body,0,600,'utf-8'));?>
			</section>
			<footer></footer>
		</article>
		<div>
			<a href="<?=$this->url('frettir')?>" class="btn btn-default">Yfirlit frétta og greina</a>
		</div>
	</div>


	<div class="image-boxes">
		<ul>
			<?php foreach($this->gallery as $item):?>
			<li>
				<img src="<?=$this->basePath("/images/300-square/{$item->name}")?>" title="<?=$item->description?>" />
			</li>
			<?php endforeach;?>
		</ul>
	</div>
</div>

<?php endif;?>

