<?php
use Stjornvisi\Properties\FileProperties;
?>

<div class="panel panel--hero">
	<div class="panel__container">
		<div class="panel__content">
			<a href="#" class="logo">
				<img src="<?=$this->basePath("/themes/2016/stylesheets/images/logo-white.png")?>" alt="Stjórnvísi">
			</a>
			<div class="box">
				<div class="box__title"><h2>Framsækin stjórnun</h2></div>
				<div class="box__content">
					<p>Boudin filet mignon jowl, short loin hamburger leberkas porchetta rump brisket ball tip. Pork andouille pork loin tenderloin shankle salami. Beef ribs flank salami andouille brisket ground round brisket bresaola hamburger ham.
						shankle. Tail tri-tip pastrami, landjaeger pork loin boudin turkey ham sirloin drumstick</p>
					<p><a href="#">Hvaða fyrirtæki eru aðilar að Stjórnvísi?</a></p>
					<p><a href="#" class="btn btn-primary">Stofna aðgang</a></p>
					<p><a href="#" class="login btn btn-info">Innskráning <i class="fa fa-unlock-alt"></i></a></p>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="panel panel--navigation">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box box--navigation">
				<div class="box__content">
					<nav>
						<a href="<?=$this->url('hopur')?>"><span>Faghópar</span></a>
						<a href="<?=$this->url('vidburdir')?>"><span>Viðburðir</span></a>
						<a href="<?=$this->url('stjornunarverdlaunin') ?>"><span>Stjórnunarverðlaunin</span></a>
						<a href="<?=$this->url('anaegjuvogin') ?>"><span>Ánægjuvogin</span></a>
						<a href="<?=$this->url('um') ?>"><span>Um Stjórnvísi</span></a>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="panel">
	<div class="panel__container">
		<div class="panel__content panel--row">
			<div class="box box--news">
				<div class="box__title"><h2>Fréttir af Stjórnvísi</h2></div>
				<div class="box__content">
					<?for ($i = 0; $i < 5; $i++):?>
						<div class="entry">
							<div class="entry__info">14.mar 2016</div>
							<div class="entry__title"><h3><a href="#">Hver vegna að mæla þjónustu?</a></h3></div>
							<div class="entry__content">
								Faghópur þjónustu - og markaðsstjórnunar hélt í samvinnu við Vodafone og Gallup erindi um tilgang og markmið ólíkra þjónustumælinga í morgun Fundarstjóri var...
							</div>
							<div class="entry__image">
								<img src="//placehold.it/270x180" alt="Placeholder">
							</div>
						</div>
					<?endfor;?>

					<div class="entry entry--simple">
						<div class="entry__info">14.mar 2016</div>
						<div class="entry__title"><h3><a href="#">Hver vegna að mæla þjónustu?</a></h3></div>
					</div>

					<div class="entry entry--simple">
						<div class="entry__info">14.mar 2016</div>
						<div class="entry__title"><h3><a href="#">Hver vegna að mæla þjónustu?</a></h3></div>
					</div>
				</div>
				<div class="box__footer">
					<a href="#"><i class="fa fa-plus-circle"></i> Skoða fleiri fréttir og pistla</a>
				</div>
			</div>
			<div class="box box--events">
				<div class="box__title"><h2>Viðburðir á næstunni</h2></div>
				<div class="box__content">
					<?for ($i = 0; $i < 3; $i++):?>
						<div class="entry">
							<div class="entry__title">
								<div class="entry__date">
									<span class="day">03</span>
									<span class="month">apr</span>
									<span class="year">2016</span>
								</div>
								<h3><a href="#">Hver vegna að mæla þjónustu?</a></h3>
								<div class="entry__info">
									<i class="fa fa-clock-o"></i> 08:30 - 09:45
									<span class="separator">/</span>
									<i class="fa fa-map-marker"></i> Kringlunni 5
								</div>
							</div>
							<div class="entry__content">
								<p>Sirloin tongue andouille cow jowl short loin filet mignon. Shankle andouille prosciutto pork alcatra brisket chicken pig swine.</p>
								<p>Pork belly short ribs leberkas salami swine tenderloin strip steak. Leberkas pig ham hock turkey, meatloaf doner prosciutto cow jerky short loin fatback.
									Tenderloin cupim bresaola kielbasa, pork loin spare ribs tongue boudin jowl meatloaf ground round pig ribeye flank ham hock. T-bone shankle chuck bacon filet mignon cupim porchetta shoulder landjaeger pig. Capicola ground round bresaola short ribs.</p>
								<p><a href="#" class="btn btn-default">Hef áhuga</a> <a href="#" class="btn btn-primary">Staðfesta mætingu</a></p>
							</div>
						</div>
					<?endfor;?>
				</div>
				<div class="box__footer">
					<a href="#"><i class="fa fa-plus-circle"></i> Skoða alla 14 viðburði næsta mánuðinn</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="panel panel--inset">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box box--carousel">
				<div class="box__jip">
					<a href="#"><i class="fa fa-plus-circle"></i> Yfirlit liðinna viðburða</a>
				</div>
				<div class="box__title"><h2>Eldri viðburðir</h2></div>
				<div class="box__content">
					<?for ($i = 0; $i < 2; $i++):?>
						<div class="entry">
							<div class="entry__info">14.mar 2016</div>
							<div class="entry__title">
								<h3><a href="#">Hver vegna að mæla þjónustu?</a></h3>
							</div>
							<div class="entry__image">
								<img src="//placehold.it/570x360" alt="Placeholder">
							</div>
							<div class="entry__content">
								Faghópur þjónustu - og markaðsstjórnunar hélt í samvinnu við Vodafone og Gallup erindi um tilgang og markmið ólíkra þjónustumælinga í morgun Fundarstjóri var
								Páll Ásgeir Guðmundsson, sviðsstjóri markaðsrannsókna Gallup fór yfir nokkrar leiðir til að mæla gæði þjónustu, og hvernig fyrirtæki skoða stöðugar umbætur með
							</div>
						</div>
					<?endfor;?>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="panel panel--groups">
	<div class="panel__container">
		<div class="panel__content panel--row">
			<div class="box">
				<div class="box__title"><h2>Yfirlit faghópa</h2></div>
				<div class="box__content">
					<ul class="legend">
						<li><i class="fa fa-calendar-o"></i>Einn eða fleiri viðburðir í vetur</li>
						<li><i class="fa fa-check"></i>Þínir hópar</li>
					</ul>
					<div class="entry">
						<div class="entry__title"><h3>Kjarnastarf Stjórnvísis fer fram í þeim 26 faghópum sem eru starfandi innan félagsins á jafnmjörgum sviðum stjórnunar.</h3></div>
						<div class="entry__content">
							<p>Tail strip steak salami, ball tip jerky tenderloin meatball. Shankle turkey shank, venison strip steak alcatra pastrami. Shankle alcatra porchetta cow drumstick kielbasa, turkey pork chop beef leberkas andouille rump pig.</p>
							<p>Flank swine alcatra bacon chicken beef kielbasa pork loin ham doner turducken ham hock pork beef ribs chuck. Andouille capicola strip steak pancetta fatback salami spare ribs kevin brisket drumstick beef ribs pastrami.</p>
							<p>T-bone pig venison, landjaeger alcatra turkey turducken short ribs ham hock kevin andouille pork chop prosciutto sirloin. Andouille tenderloin beef ribs, brisket alcatra chuck pork turkey sausage flank ball tip.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="box">
				<div class="box__content">
					<?for ($i = 0; $i < 3; $i++):?>
					<div class="entry entry--hoverable">
						<div class="entry__title">
							<div class="entry__status">
								<i class="fa fa-check"></i>
							</div>
							<h4>
								Breytingastjórnun
								<span class="fa-stack">
									<i class="fa fa-calendar-o fa-stack-2x"></i>
									<i class="fa-stack-1x"><?=$i+1?></i>
								</span>
							</h4>
						</div>
						<div class="entry__content">
							<div class="event">
								<div class="event__label"><h4><i class="fa fa-calendar-o"></i>Næsti viðburður</h4></div>
								<div class="event__info">
									<span class="entry__date">þri 19.jan 2016</span>
									<span class="separator">/</span>
									<span class="event__time">08:30 - 09:45</span>
								</div>
								<div class="event__title"><h5><a href="#">Mannauðsstjórnun og þjónandi forysta</a></h5></div>
								<div class="event__details"><a href="#">5 viðburðir síðustu 12 mánuði</a></div>
								<div class="event__content">
									<h4>Stjórn</h4>
									<p>
										Kamilla Reynisdóttir, Eimskip<br>
										Ásdís Kristinsdóttir, Orkuveita Reykjavíkur<br>
										Aðalheiður Sigursveinsdóttir, Expectus<br>
										Björn Sighvatsson, Landsbankinn<br>
										Davíð Lúðvíksson, Samtök iðnaðarins<br>
										Guðrún B Sigurbjörnsdóttir, Landspítali - háskólasjúkrahús
									</p>
									<a href="#" class="btn btn-default">Afskrá mig úr þessum hóp</a>
								</div>
							</div>
						</div>
					</div>
					<?endfor?>
				</div>
			</div>
		</div>
	</div>
</div>
