<?php
$this->headTitle( $this->group->name );
$this->headTitle('Hópur');


$this->headMeta()->setProperty('og:title', $this->group->name);
$this->headMeta()->setProperty('og:site_name', 'Stjórnvísi');
$this->headMeta()->setProperty('og:type', 'article');
$this->headMeta()->setProperty('og:description', mb_substr($this->group->summary,0,200));
$this->headMeta()->setProperty('og:url', 'http://'.$_SERVER['HTTP_HOST'].$this->url('hopur/index',array('id'=>$this->group->url)));

?>
<div class="layout layout--three-columns-reverse page-group">
	<section class="layout__section">
		<div class="page-group__header">
			<h1 class="page-group__headline"><?=$this->group->name;?></h1>
			<h2 class="layout__headline page-group__period">Starfsár <?=$this->range->from->format('Y')?> - <?=$this->range->to->format('Y')?></h2>
			<?php if($this->logged_in):?>
				<?php if( $this->access->type === null ):?>
					<a href="<?=$this->url('hopur/register',array('id'=>$this->group->url,'type'=>1))?>" class="btn btn-warning page-group__register">Skrá í hóp</a>
				<?php else:?>
					<a href="<?=$this->url('hopur/register',array('id'=>$this->group->url,'type'=>0))?>" class="btn btn-danger page-group__register">Afskrá úr hópi</a>
				<?php endif;?>
			<?php else:?>
				<a href="<?=$this->url('auth')?>" class="btn btn-danger page-group__register">Skrá í hóp</a>
			<?php endif;?>
		</div>
		<div class="layout__data">
			<h2 id="vidburdir" class="layout__headline">Viðburðir</h2>
			<ul class="block-list block-list--separator">
				<?php foreach($this->events as $event):?>
					<li id="vidburdur-<?=$event->id?>">
						<article class="block-element <?=($event->event_date < new DateTime())?'archived':''?>">
							<header class="block-element__header">
								<time class="block-element__time" datetime="<?=$event->event_date->format('c');?>">
									<?=$this->date($event->event_date)?> &middot <?=($event->event_time)?$event->event_time->format('H:i'):'';?> - <?=($event->event_end)?$event->event_end->format('H:i'):'';?>
								</time>
								<h1><a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>"><?=$event->subject?></a></h1>
							</header>
							<section class="block-element__body">
								<?php if($event->avatar):?>
									<a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>" class="block-element__poster">
										<img src="<?=$this->basePath("/images/300-square/{$event->avatar}")?>" alt="mynd með viðburði" />
									</a>
								<?php endif;?>
								<?=$this->paragrapher( mb_substr($event->body,0,300,'utf-8'));?>
								<a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>" class="block-element__more">meira</a>
							</section>
							<?php if( $this->logged_in && $event->can_attend ):?>
							<footer>
								<?php if( $event->attending === null):?>
									<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>1))?>" class="attending yes" title="Skrá mætingu">mæti</a>
									<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>0))?>" class="attending no" title="Afskrá mætingu">mæti ekki</a>
								<?php elseif($event->attending == 0):?>
									<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>1))?>" class="attending yes" title="Skrá mætingu">mæti</a>
									<span class="attending no" title="Afskrá mætingu">mæti ekki</span>
								<?php elseif($event->attending == 1):?>
									<span class="attending yes" title="Skrá mætingu">mæti</span>
									<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>0))?>" class="attending no" title="Afskrá mætingu">mæti ekki</a>
								<?php endif;?>
							</footer>
							<?php endif;?>
						</article>
					</li>
				<?php endforeach;?>
			</ul>
		</div>
		<div class="layout__meta">
			<h2 id="frettir" class="layout__headline">Fréttir</h2>
			<ul class="block-list block-list--separator">
				<?php foreach($this->news as $news):?>
					<li>
						<article class="block-element">
							<header class="block-element__header">
								<time class="block-element__time" datetime="<?=$news->created_date->format('c')?>">
									<?=$this->date($news->created_date,\Stjornvisi\View\Helper\Date::FORMAT_DATE_TIME);?>
								</time>
								<h1><a href="<?=$this->url('frettir/index',array('id'=>$news->id))?>"><?=$news->title?></a></h1>
							</header>
							<section class="block-element__body">
								<?php if($news->avatar):?>
									<a href="<?=$this->url('frettir/index',array('id'=>$news->id))?>" class="block-element__poster">
										<img src="<?=$this->basePath("/images/300-square/{$news->avatar}")?>" alt="mynd með frétt" />
									</a>
								<?php endif;?>
								<?=$this->paragrapher( mb_substr($news->body,0,300,'utf-8'));?>
								<a href="<?=$this->url('frettir/index',array('id'=>$news->id))?>" class="block-element__more">meira</a>
							</section>
							<aside>
							</aside>
							<footer></footer>
						</article>
					</li>
				<?php endforeach;?>
			</ul>
		</div>
		<div class="page-group__description page-group__separator">
			<h2 id="um" class="page-group__subline">Um <?=$this->group->name;?></h2>
			<?=$this->paragrapher($this->group->body); ?>
			<div id="fb-root"></div>
			<script>(function(d, s, id) {
					var js, fjs = d.getElementsByTagName(s)[0];
					if (d.getElementById(id)) return;
					js = d.createElement(s); js.id = id;
					js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=1645847542309046&version=v2.0";
					fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));</script>
			<div class="fb-like" data-href="http://<?=$_SERVER['HTTP_HOST']?><?=$this->url('hopur/index',array('id'=>$this->group->url))?>" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>

		</div>
		<div class="page-group__members page-group__separator">
			<h2 id="medlimir" class="page-group__subline">Meðlimir</h2>


			<div class="page-group__members-member">
				<h2 class="layout__headline">Stjórn</h2>
				<?php
				//SOME LOGIC
				//	it would be super cool if I didn't have to do this here,
				//	but I need to split the list up, and this has nothing to
				//	with domain logic and everything with presentation
				//	so I have to make the view dirty with some PHP code
				$user_chunk =  (count($this->managers))
					? array_chunk($this->managers,ceil(count($this->managers) / 3))
					: array() ;
				?>
				<?php foreach($user_chunk as $chunk):?>
				<ul>
					<?php foreach( $chunk as $user ):?>
						<li class="page-group__members-item <?=($user->type==2)?'page-group__members-item--em':''?>" data-search="<?=$user->name;?>">
							<h3><a href="<?=$this->url('notandi/index',array('id'=>$user->id))?>"><?=$user->name;?></a></h3>
							<span class="page-group__members-item--title"><?=($user->type==2)?'Formaður':'Stjórnandi'?></span>
							<a href="mailto:<?=$user->email;?>" class="page-group__members-item--email"><?=$user->email;?></a>
                            <?php if($user->company_id):?>
							<span><a href="<?=$this->url('fyrirtaeki/index', ['id' => $user->company_id])?>"><?=$user->company_name;?></a></span>
                            <?php endif;?>
							<span><?=$user->title;?></span>
							<?php if($this->access->is_admin || $this->access->type >= 1):?>
								<stjonvisi-control class="inline">
									<a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>1,'user_id'=>$user->id))?>"><i class="icon-minus"></i> stjórnandi</a>
									<a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>0,'user_id'=>$user->id))?>"><i class="icon-minus"></i> meðlimur</a>
								</stjonvisi-control>
							<?php endif;?>
						</li>
					<?php endforeach;?>
				</ul>
				<?php endforeach;?>
			</div>

			<div class="page-group__members-member">
				<?php if($this->access->is_admin || $this->access->type >= 1):?>
					<h2 class="layout__headline">Meðlimir (<?=count($this->users)?>)</h2>
					<?php
						//SOME LOGIC
						//	it would be super cool if I didn't have to do this here,
						//	but I need to split the list up, and this has nothing to
						//	with domain logic and everything with presentation
						//	so I have to make the view dirty with some PHP code
						$user_chunk =  (count($this->users))
							? array_chunk($this->users,ceil(count($this->users) / 3))
							: array() ;
					?>

					<?php foreach( $user_chunk as $chunk ):?>
					<ul>
						<?php foreach($chunk as $user):?>
							<li class="page-group__members-item" data-search="<?=$user->name;?>">
								<h3><a href="<?=$this->url('notandi/index',array('id'=>$user->id))?>"><?=$user->name;?></a></h3>
								<span><?=$user->title;?></span>
                                <?php if($user->company_id):?>
                                <span><a href="<?=$this->url('fyrirtaeki/index', ['id' => $user->company_id])?>"><?=$user->company_name;?></a></span>
                                <?php endif;?>
								<?php if($this->access->is_admin || $this->access->type >= 1):?>
									<stjonvisi-control class="inline">
										<a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>2,'user_id'=>$user->id))?>"><i class="icon-plus"></i>  formaður</a>
										<a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>1,'user_id'=>$user->id))?>"><i class="icon-plus"></i>  stjórnandi</a>
									</stjonvisi-control>
								<?php endif;?>
							</li>
						<?php endforeach;?>
					</ul>
					<?php endforeach;?>
				<?php endif;?>
			</div>
		</div>

	</section>
	<aside class="layout__aside">
		<?php if($this->access->is_admin || $this->access->type >= 1):?>
			<stjonvisi-control>
				<a href="<?=$this->url('hopur/update',array('id'=>$this->group->url));?>" class="update"><i class="icon-check"></i> uppfæra</a>
				<?php if($this->access->is_admin):?>
					<a href="<?=$this->url('hopur/delete',array('id'=>$this->group->url));?>" class="update"><i class="icon-close"></i> eyða</a>
				<?php endif;?>
				<a href="<?=$this->url('frettir/create',array('id'=>$this->group->id))?>"><i class="icon-plus"></i> frétt</a>
				<a href="<?=$this->url('vidburdir/create',array('id'=>$this->group->id))?>"><i class="icon-plus"></i>  viðburð</a>
				<a href="<?=$this->url('hopur/send-mail',array('id'=>$this->group->url,'type'=>'allir'));?>" ><i class="icon-envelope"></i> allir</a>
				<a href="<?=$this->url('hopur/send-mail',array('id'=>$this->group->url,'type'=>'formenn'));?>"><i class="icon-envelope"></i> stjórnendur</a>
				<a href="<?=$this->url('hopur/user-export',array('id'=>$this->group->url));?>"><i class="icon-list"></i> meðlimalisti</a>
				<a href="<?=$this->url('hopur/board-export',array('id'=>$this->group->url));?>"><i class="icon-list"></i> stjórnendalisti</a>
				<a href="<?=$this->url('hopur/chair-export',array('id'=>$this->group->url));?>"><i class="icon-list"></i> formannalisti</a>
				<a href="<?=$this->url('hopur/event-export',array('id'=>$this->group->url));?>"><i class="icon-list"></i> viðburðalisti</a>
			</stjonvisi-control>
		<?php endif;?>
		<div class="page-group__summary">
			<?=$this->paragrapher($this->group->summary);?>
		</div>

		<h1 class="layout__headline">Fyrri starfsár</h1>
		<ul class="page-group__years">
			<?php foreach($this->range->range as $group):?>
				<li><a href="<?=$this->url('hopur/index',array('id'=>$this->group->url,'range'=>$group[0].'-'.$group[1]))?>"><?=$group[0]?> - <?=$group[1]?></a></li>
			<?php endforeach;?>
		</ul>

		<h1 class="layout__headline">Yfirlit</h1>
		<ul class="page-group__years">
			<li><a href="#frettir" data-scroll>Fréttir (<?=count($this->news)?>)</a></li>
			<li><a href="#vidburdir" data-scroll>Viðburðir (<?=count($this->events)?>)</a></li>
			<li><a href="#um" data-scroll>Um <?=$this->group->name_short?></a></li>
			<?php if($this->access->is_admin || $this->access->type >= 1):?>
			<li><a href="#medlimir" data-scroll>Meðlimir</a></li>
			<?php endif; ?>
		</ul>

		<h1 class="layout__headline">Straumar</h1>
		<ul class="page-group__years">
			<li><a href="<?=$this->url('rss/rss-news',array('name'=>$this->group->url))?>" title="RSS fréttastraumur" target="_blank">Fréttir <i class="icon-rss"></i></a></li>
			<li><a href="<?=$this->url('rss/rss-events',array('name'=>$this->group->url))?>" title="RSS viðburðastraumur" target="_blank">Viðburðir <i class="icon-rss"></i></a></li>
			<li><a href="ical://<?=$_SERVER['HTTP_HOST']?><?=$this->url('hopur/ical',array('id'=>$this->group->url))?>" title="iCal viðburðastraumur" target="_blank">Viðburðir <i class="icon-calendar-o"></i></a></li>
		</ul>

		<h1 class="layout__headline">Viðburðadagatal</h1>
		<ul class="page-group__calendar block-list block-list--less">
		<?php foreach($this->events as $event):?>
			<li class="block-item">
				<time class="block-item__time" datetime="<?=$event->event_date->format('c');?>">
					<?=$this->date($event->event_date)?>
				</time>
				<a href="#vidburdur-<?=$event->id?>" data-scroll><?=$event->subject?></a>
			</li>
		<?php endforeach;?>
		</ul>



	</aside>
</div>
