<div class="layout layout--three-columns-reverse page-group">
	<section class="layout__section">
		<div class="page-group__header">
			<h1 class="page-group__headline"><?=$this->group->name;?></h1>
			<h2>Starfsár <?=$this->range->from->format('Y')?> - <?=$this->range->to->format('Y')?></h2>
			<?php if($this->logged_in):?>
				<?php if( $this->access->type === null ):?>
					<a href="<?=$this->url('hopur/register',array('id'=>$this->group->url,'type'=>1))?>" class="btn btn-warning page-group__register">Skrá í hóp</a>
				<?php else:?>
					<a href="<?=$this->url('hopur/register',array('id'=>$this->group->url,'type'=>0))?>" class="btn btn-danger page-group__register">Afskrá úr hópi</a>
				<?php endif;?>
			<?php else:?>
				<a href="<?=$this->url('auth')?>" class="btn btn-danger page-group__register">Skrá í hóp</a>
			<?php endif;?>
		</div>
		<div class="layout__data">
			<h2 id="vidburdir" class="layout__headline">Viðburðir - <a href="<?=$this->url('rss/rss-events',array('name'=>$this->group->url))?>">rss</a></h2>
			<ul class="block-list block-list--separator">
				<?php foreach($this->events as $event):?>
					<li id="vidburdur-<?=$event->id?>">
						<article class="block-element <?=($event->event_date < new DateTime())?'archived':''?>">
							<header class="block-element__header">
								<time class="block-element__time" datetime="<?=$event->event_date->format('c');?>">
									<?=$this->date($event->event_date)?> &middot <?=$event->event_time->format('H:m');?> - <?=$event->event_end->format('H:m');?>
								</time>
								<h1><a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>"><?=$event->subject?></a></h1>
							</header>
							<section class="block-element__body">
								<?php if($event->avatar):?>
									<a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>" class="block-element__image">
										<img src="<?=$this->basePath("/images/100/{$event->avatar}")?>" alt="mynd með viðburði" />
									</a>
								<?php endif;?>
								<?=$this->paragrapher( mb_substr($event->body,0,300,'utf-8'));?>
								<a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>" class="block-element__more">meira</a>
							</section>
							<!--aside class="block-element__aside">
								<ul class="block-element__tags">
									<?php if( count($event->groups) == 0 ):?>
										<li><span class="label label-default">Stjónvísisviðburður</span></li>
									<?php else:?>
										<?php foreach($event->groups as $group):?>
											<li><a class="label label-default" href="/hopur/<?=$group->url;?>"><?=$group->name_short;?></a></li>
										<?php endforeach;?>
									<?php endif; ?>
								</ul>
							</aside-->
							<!--footer>
							<?php if($event->attending === null):?>
								<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>1))?>" class="attending yes" title="Skrá mætingu">mæti</a>
								<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>0))?>" class="attending no" title="Afskrá mætingu">mæti ekki</a>
							<?php elseif($event->attending == 0):?>
								<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>1))?>" class="attending yes" title="Skrá mætingu">mæti</a>
								<span class="attending no" title="Afkrá mætingu">mæti ekki</span>
							<?php elseif($event->attending == 1):?>
								<span class="attending yes" title="Skrá mætingu">mæti</span>
								<a href="<?=$this->url('vidburdir/attending',array('id'=>$event->id,'type'=>0))?>" class="attending no" title="Afskrá mætingu">mæti ekki</a>
							<?php endif;?>
						</footer-->
						</article>
					</li>
				<?php endforeach;?>
			</ul>
		</div>
		<div class="layout__meta">
			<h2 id="frettir" class="layout__headline">Fréttir  - <a href="<?=$this->url('rss/rss-news',array('name'=>$this->group->url))?>">rss</a></h2>
			<ul class="block-list block-list--separator">
				<?php foreach($this->news as $news):?>
					<li>
						<article class="block-element">
							<header class="block-element__header">
								<time class="block-element__time" datetime="<?=$news->created_date->format('c')?>">
									<?=$this->date($news->created_date,\Stjornvisi\View\Helper\Date::FORMAT_DATE_TIME);?>
								</time>
								<h1><a href="<?=$this->url('frettir/index',array('id'=>$news->id))?>"><?=$news->title?></a></h1>
							</header>
							<section class="block-element__body">
								<?php if($news->avatar):?>
									<a href="<?=$this->url('frettir/index',array('id'=>$news->id))?>" class="block-element__image">
										<img src="<?=$this->basePath("/images/100/{$news->avatar}")?>" alt="mynd með frétt" />
									</a>
								<?php endif;?>
								<?=$this->paragrapher( mb_substr($news->body,0,300,'utf-8'));?>
							</section>
							<aside>
							</aside>
							<footer></footer>
						</article>
					</li>
				<?php endforeach;?>
			</ul>
		</div>
		<div class="page-group__description page-group__separator">
			<h2 id="um" class="page-group__subline">Um <?=$this->group->name;?></h2>
			<h3 class="layout__headline">Markmið</h3>
			<?=$this->paragrapher($this->group->objective); ?>
			<h3 class="layout__headline">Hvað er <?=$this->group->name;?></h3>
			<?=$this->paragrapher($this->group->how_operates); ?>
			<h3 class="layout__headline">Hvernig starfar hópurinn</h3>
			<?=$this->paragrapher($this->group->for_whom); ?>
		</div>

		<?php if($this->access->is_admin || $this->access->type >= 1):?>
			<div class="page-group__members page-group__separator">
				<h2 id="medlimir" class="page-group__subline">Meðlimir</h2>
				<div class="page-group__members-head">
					<h2 class="layout__headline">Formenn (<?=count($this->chairmen)?>)</h2>
					<ul>
						<?php foreach($this->chairmen as $user):?>
							<li class="page-group__members-item">
								<h3><a href="<?=$this->url('notandi/index',array('id'=>$user->id))?>"><?=$user->name;?></a></h3>
								<span><?=$user->title;?></span>
								<?php if($this->access->is_admin || $this->access->type >= 1):?>
									<stjonvisi-control class="inline">
										<ul class="dropdown-menu" role="menu">
											<li><a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>1,'user_id'=>$user->id))?>">Gera að stjórnanda</a></li>
											<li><a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>0,'user_id'=>$user->id))?>">Gera að meðlim</a></li>
										</ul>
									</stjonvisi-control>
								<?php endif;?>
							</li>
						<?php endforeach;?>
					</ul>
					<h2 class="layout__headline">Stjórnendur (<?=count($this->managers)?>)</h2>
					<ul>
						<?php foreach($this->managers as $user):?>
							<li class="page-group__members-item">
								<h3><a href="<?=$this->url('notandi/index',array('id'=>$user->id))?>"><?=$user->name;?></a></h3>
								<span><?=$user->title;?></span>
								<?php if($this->access->is_admin || $this->access->type >= 1):?>
									<stjonvisi-control class="inline">
										<ul class="dropdown-menu" role="menu">
											<li><a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>2,'user_id'=>$user->id))?>">Gera að formanni</a></li>
											<li><a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>0,'user_id'=>$user->id))?>">Gera að meðlim</a></li>
										</ul>
									</stjonvisi-control>
								<?php endif;?>
							</li>
						<?php endforeach;?>
					</ul>
				</div>
				<div class="page-group__members-member">
					<?php if($this->access->is_admin || $this->access->type != null):?>
						<h2 class="layout__headline">Meðlimir (<?=count($this->users)?>)</h2>
						<?php
							$user_chunk = array_chunk($this->users,ceil(count($this->users) / 2));
						?>

						<?php foreach( $user_chunk as $chunk ):?>
						<ul>
							<?php foreach($chunk as $user):?>
								<li class="page-group__members-item">
									<h3><a href="<?=$this->url('notandi/index',array('id'=>$user->id))?>"><?=$user->name;?></a></h3>
									<span><?=$user->title;?></span>
									<?php if($this->access->is_admin || $this->access->type >= 1):?>
										<stjonvisi-control class="inline">
											<ul class="dropdown-menu" role="menu">
												<li><a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>2,'user_id'=>$user->id))?>">Gera að formanni</a></li>
												<li><a href="<?=$this->url('hopur/user-status',array('id'=>$this->group->url,'type'=>1,'user_id'=>$user->id))?>">Gera að stjórnanda</a></li>
											</ul>
										</stjonvisi-control>
									<?php endif;?>
								</li>
							<?php endforeach;?>
						</ul>
						<?php endforeach;?>
					<?php endif;?>
				</div>
			</div>
		<?php endif;?>


	</section>
	<aside class="layout__aside">

		<div class="page-group__summary">
			<?=$this->paragrapher($this->group->description);?>
		</div>

		<h1 class="layout__headline">Fyrri starfsár</h1>
		<ul class="page-group__years">
			<?php foreach($this->range->range as $group):?>
				<li><a href="<?=$this->url('hopur/index',array('id'=>$this->group->url,'range'=>$group[0].'-'.$group[1]))?>"><?=$group[0]?> - <?=$group[1]?></a></li>
			<?php endforeach;?>
		</ul>

		<h1 class="layout__headline">Yfirlit</h1>
		<ul class="page-group__years">
			<li><a href="#frettir" data-scroll>Fréttir (<?=count($this->news)?>)</a></li>
			<li><a href="#vidburdir" data-scroll>Viðburðir (<?=count($this->events)?>)</a></li>
			<li><a href="#um" data-scroll>Um <?=$this->group->name_short?></a></li>
			<?php if($this->access->is_admin || $this->access->type >= 1):?>
			<li><a href="#medlimir" data-scroll>Meðlimir</a></li>
			<?php endif; ?>
		</ul>

		<h1 class="layout__headline">Viðburðadagatal</h1>
		<ul class="page-group__calendar block-list block-list--less">
		<?php foreach($this->events as $event):?>
			<li class="block-item">
				<time class="block-item__time" datetime="<?=$event->event_date->format('c');?>">
					<?=$this->date($event->event_date)?>
				</time>
				<a href="#vidburdur-<?=$event->id?>" data-scroll><?=$event->subject?></a>
			</li>
		<?php endforeach;?>
		</ul>

		<?php if($this->access->is_admin || $this->access->type >= 1):?>
			<stjonvisi-control>
				<a href="<?=$this->url('hopur/update',array('id'=>$this->group->url));?>">Uppfæra lýsingu</a>
				<a href="<?=$this->url('hopur/send-mail',array('id'=>$this->group->url,'type'=>'allir'));?>">Senda póst á alla</a>
				<a href="<?=$this->url('hopur/send-mail',array('id'=>$this->group->url,'type'=>'formenn'));?>">Senda póst á stjórnendur</a>
				<a href="<?=$this->url('hopur/user-export',array('id'=>$this->group->url));?>">Meðlimalisti (csv)</a>
				<?php if($this->access->is_admin):?>
					<a href="<?=$this->url('hopur/delete',array('id'=>$this->group->url));?>">Eyða faghópi</a>
					<a href="<?=$this->url('frettir/create',array('id'=>$this->group->id))?>">Stofna frétt</a>
					<a href="<?=$this->url('vidburdir/create',array('id'=>$this->group->id))?>">Stofna viðburð</a>
				<?php endif;?>
			</stjonvisi-control>
		<?php endif;?>

	</aside>
</div>



<!--pre><?php print_r($this->group);?></pre-->
<!--pre><?php print_r($this->news);?></pre-->
<!--pre><?php print_r($this->events);?></pre-->
