<?php
/**
 * Created by PhpStorm.
 * User: einarvalur
 * Date: 2/18/14
 * Time: 2:52 PM
 */

use Stjornvisi\Properties\FileProperties;

?>

<?if (!isset($this->skipBreadcrumbs)):?>
<div class="panel panel--breadcrumbs">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__content">
					<a href="/">Forsíða</a>
					<span class="separator">/</span>
					Faghópar
				</div>
			</div>
		</div>
	</div>
</div>
<?endif?>

<div class="panel panel--columns-two panel--groups<?php if ($this->skipBreadcrumbs):?> panel--inset<?php endif?>">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__title"><h2>Yfirlit faghópa</h2></div>
				<div class="box__content hoverable--fade">
					<div class="entry">
						<div class="entry__title"><h3>Kjarnastarf Stjórnvísi er í faghópunum. Í Stjórnvísi eru starfandi tæplega 20 faghópar undir forystu sterkra stjórna sem koma frá aðildarfyrirtækjum félagsins.</h3></div>
						<div class="entry__content">
							<p>Með því að skrá þig í faghóp færðu sendar tilkynningar um viðburði, gefst kostur á að skoða ítarefni frá viðburðum og fá áhugaverðar fréttir. Engin takmörk eru fyrir því hve marga faghópa er hægt að skrá sig í.</p>
						</div>
					</div>
				</div>
			</div>


			<div class="box">
				<div class="box__content">
					<ul class="legend">
						<li><i class="fa fa-calendar-o"></i>Einn eða fleiri viðburðir síðustu 3 mánuði</li>
						<li><i class="fa fa-check"></i>Þínir hópar</li>
					</ul>

					<? foreach ($this->groups_all as $group) : ?>
						<div class="entry entry--hoverable">
							<div class="entry__title">
								<div class="entry__status">
									<i class="fa<?=(null !== $group->user_id) ? ' fa-check' : ''?>"></i>
								</div>
								<h4>
									<a href="<?=$this->url('hopur/index', array('id' => $group->url))?>"><?=$group->name_short?></a>
									<? if ($group->event_count > 0): ?>
										<span class="fa-stack">
										<i class="fa fa-calendar-o fa-stack-2x"></i>
										<i class="fa-stack-1x"><?=$group->event_count?></i>
									</span>
									<? endif; ?>
									<? if (null === $group->user_id) : ?>
										<a href="<?=$this->url('hopur/register', array('id' => $group->url, 'type' => 1))?>"
										   class="btn btn-default">Skrá í hóp</a>
									<? else:?>
										<a href="<?=$this->url('hopur/register', array('id' => $group->url, 'type' => 0))?>"
										   class="btn btn-default">Yfirgefa hóp</a>
									<? endif ?>
								</h4>
							</div>
								<div class="entry__content">
									<? if (count($group->events) || $group->event_count || count($group->board)) : ?>
									<div class="event">
										<div class="event__summary"><?=$group->summary?></div>
										<? if ($group->event_count > 0) : ?>
											<div class="event__details">
												<div class="event__count">
													Viðburðir síðustu 3 mánuði
													<span class="fa-stack">
														<i class="fa fa-calendar-o fa-stack-2x"></i>
														<i class="fa-stack-1x"><?=$group->event_count?></i>
													</span>
												</div>
												<h4>Viðburðir</h4>
											</div>
										<? endif; ?>
										<? if (count($group->events)) : ?>
											<? /** @var \Stjornvisi\Service\Event $nextEvent */
											$nextEvent = array_pop($group->events) ?>
											<div class="event__info">
												<span
													class="entry__date"><?=$this->date($nextEvent->event_date)?></span>
												<span class="separator">/</span>
										<span class="event__time">
										<? if ($nextEvent->event_time) : ?>
											<?=$nextEvent->event_time->format("H:i")?>
											<? if ($nextEvent->event_end) : ?>
												- <?=$nextEvent->event_end->format("H:i")?>
											<? endif; ?>
										<? endif; ?>
										</span>
											</div>
											<div class="event__title">
												<h5>
													<a href="<?=$this->url('vidburdir/index', array('id' => $nextEvent->id))?>"><?=$nextEvent->subject?></a>
												</h5>
											</div>
										<? endif; ?>
										<? if (count($group->board)) : ?>
											<div class="event__content">
												<h4>Stjórn</h4>
												<p>
													<? $i = 0;
													foreach ($group->board as $member) : ?>
														<?=($i != 0) ? '<br>' : ''?>
														<a href="<?=$this->url('notandi', array('id' => $member->id))?>"><?=$member->name?></a>,
														<a href="<?=$this->url('fyrirtaeki', array('id' => $member->company_id))?>"><?=$member->company_name?></a>
														<? $i++; endforeach; ?>
												</p>
											</div>
										<? endif; ?>
										<div class="event__footer">
											<a href="<?=$this->url('hopur/index', array('id' => $group->url))?>" class="btn btn-primary">Skoða nánar</a>
										</div>
									</div>
									<? else: ?>
										<div class="event">
											<div class="event__summary"><p>Hópurinn er ekki virkur.</p></div>
										</div>
									<? endif; ?>
								</div>
						</div>
					<? endforeach; ?>
				</div>
			</div>
		</div>
	</div>
</div>


