<?php
/**
 * Created by PhpStorm.
 * User: einarvalur
 * Date: 2/18/14
 * Time: 2:52 PM
 */
?>
<div class="layout layout--three-columns">
	<section class="layout__section">
		<h1>Hópar (<?=count($this->groups_all);?>)</h1>
		<ul class="block-list">
		<?php foreach( $this->groups_all as $group ):?>
			<li>
			<article class="block-element group-block-list">
				<header class="block-element__header group-block-list__header">
					<h1><a href="<?=$this->url('hopur/index',array('id'=>$group->url))?>"><?=$group->name?></a></h1>
				</header>
				<aside class="block-element__aside header group-block-list__aside">
					<ul>
						<?php foreach($group->events as $event):?>
							<li>
								<article class="block-element">
									<header class="block-element__header">
										<h2><a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>"><?=$event->subject?></a></h2>
										<time class="block-element__time"><?=$event->event_date->format('Y-m-d');?></time>
									</header>
									<section class="block-element__body">
									<?php if($event->avatar):?>
										<a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>" class="block-element__image">
											<img src="<?=$this->basePath("/images/60/{$event->avatar}")?>" />
										</a>
										<?=$this->paragrapher( mb_substr($event->body,0,100,'utf-8').'&hellip;' );?>
									<?php endif;?>
									</section>

								</article>
							</li>
						<?php endforeach;?>
					</ul>
				</aside>
				<section class="block-element__body header group-block-list__body">
					<?=$this->paragrapher($group->description);?>
				</section>
			</article>
		<?php endforeach;?>
			</li>
		</ul>
	</section>
	<aside class="layout__aside">

	</aside>
</div>


