<?php
$this->headTitle('Liðnir viðburðir');
use \Stjornvisi\View\Helper\Date;
?>

<div class="panel panel--breadcrumbs">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__content">
					<a href="/">Forsíða</a>
					<span class="separator">/</span>
					<a href="/hopur">Faghópar</a>
					<span class="separator">/</span>
					<a href="/hopur/<?=$this->group->url?>"><?=$this->group->name?></a>
					<span class="separator">/</span>
					<a href="/hopur">Liðnir viðburðir</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="panel">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box box--events">
				<div class="box__title"><h2><?=$this->group->name?>: Liðnir viðburðir</h2></div>
				<div class="box__content">
					<? /** @var \Stjornvisi\Service\Event $event */ foreach ($this->events as $event) :?>
						<div class="entry">
							<div class="entry__title">
								<div class="entry__date">
									<span class="day"><?=$this->date($event->event_date, Date::FORMAT_DAY)?>.</span>
									<span class="month"><?=$this->date($event->event_date, Date::FORMAT_MONTH)?></span>
									<span class="year"><?=$this->date($event->event_date, Date::FORMAT_YEAR)?></span>
								</div>
								<h3><a href="<?=$this->url('vidburdir/index',array('id'=>$event->id))?>"><?=$event->subject?></a></h3>
								<div class="entry__info">
									<i class="fa fa-clock-o"></i>
									<? if($event->event_time) : ?>
										<?=$event->event_time->format("H:i")?>
										<? if($event->event_end) : ?>
											- <?=$event->event_end->format("H:i")?>
										<? endif; ?>
									<? endif; ?>
									<? if($event->location) : ?>
										<span class="separator">/</span>
										<i class="fa fa-map-marker"></i> <?=$event->location?>
									<? endif; ?>
								</div>
							</div>
							<div class="entry__content">
								<?=$this->paragrapher(mb_substr($event->body,0,200,'utf-8').'&#8230;'  );?>
							</div>
						</div>
					<?endforeach?>
				</div>
			</div>
		</div>
	</div>
</div>