<div class="panel panel--navigation panel--footer-navigation">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box box--navigation">
				<div class="box__content">
					<nav>
						<a href="<?=$this->url('hopur')?>"><span>Faghópar</span></a>
						<a href="<?=$this->url('vidburdir')?>"><span>Viðburðir</span></a>
						<a href="<?=$this->url('stjornunarverdlaunin') ?>"><span>Stjórnunarverðlaunin</span></a>
						<a href="<?=$this->url('anaegjuvogin') ?>"><span>Ánægjuvogin</span></a>
						<a href="<?=$this->url('um') ?>"><span>Um Stjórnvísi</span></a>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>

<footer role="footer" class="panel panel--footer">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box">
				<div class="box__content">
					<address>
						<span>STJÓRNVÍSI EHF</span>
						<span>Innovation House</span>
						<span>Eiðistorgi 13-15</span>
						<span>170 Seltjarnarnes</span><br>
						<span>Kt: 650686-1609</span>
						<span><a href="mailto:stjornvisi@stjornvisi.is">stjornvisi@stjornvisi.is</a></span>
						<span><i class="fa fa-phone"></i> 533-5666</span>
						<span><i class="fa fa-mobile"></i> 840-4990</span>
					</address>
				</div>
			</div>

			<div class="box">
				<div class="box__content">
					<a href="https://www.facebook.com/Stjornvisi" target="_blank" title="Síða Stjórnvísi á Facebook">
						<i class="fa fa-facebook-f"></i></a>
				</div>
			</div>
		</div>
	</div>
</footer>
