<header class="panel panel--hero panel--slim">
	<div class="panel__container">
		<div class="panel__content">
			<a href="/" class="logo">
				<h1>Stjórnvísi</h1>
				<img src="<?=$this->basePath("/themes/2016/stylesheets/images/logo-white.png")?>" alt="Stjórnvísi">
			</a>
			<?if(!$this->identity):?>
			<div class="box">
				<div class="box__content">
					<a href="/adgangur/stofna" class="btn btn-primary">Stofna aðgang</a>
					<a href="/innskra" class="login btn btn-info">Innskráning <i class="fa fa-unlock-alt"></i></a>
				</div>
			</div>
			<?endif?>
		</div>
	</div>
</header>
