<div class="panel panel--navigation">
	<div class="panel__container">
		<div class="panel__content">
			<div class="box box--navigation">
				<div class="box__content">
					<nav>
						<a href="<?=$this->url('hopur')?>"><span>Faghópar</span></a>
						<a href="<?=$this->url('vidburdir')?>"><span>Viðburðir</span></a>
						<a href="<?=$this->url('stjornunarverdlaunin') ?>"><span>Stjórnunarverðlaunin</span></a>
						<a href="<?=$this->url('anaegjuvogin') ?>"><span>Ánægjuvogin</span></a>
						<a href="<?=$this->url('um') ?>"><span>Um Stjórnvísi</span></a>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
