<?php echo $this->doctype(); ?>
<html lang="is">
<head>
	<meta charset="utf-8">
	<?= $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
	<meta name="msapplication-TileColor" content="#292468">
	<meta name="msapplication-TileImage" content="<?=$this->basePath("favicons/mstile-144x144.png");?>">
	<meta name="theme-color" content="#292468">
	<?= $this->headTitle('Stjórnvísi ')->setSeparator(' / ')->setAutoEscape(false) ?>

	<link rel="apple-touch-icon" sizes="57x57" href="<?=$this->basePath("favicons/apple-touch-icon-57x57.png");?>">
	<link rel="apple-touch-icon" sizes="60x60" href="<?=$this->basePath("favicons/apple-touch-icon-60x60.png");?>">
	<link rel="apple-touch-icon" sizes="72x72" href="<?=$this->basePath("favicons/apple-touch-icon-72x72.png");?>">
	<link rel="apple-touch-icon" sizes="76x76" href="<?=$this->basePath("favicons/apple-touch-icon-76x76.png");?>">
	<link rel="apple-touch-icon" sizes="114x114" href="<?=$this->basePath("favicons/apple-touch-icon-114x114.png");?>">
	<link rel="apple-touch-icon" sizes="120x120" href="<?=$this->basePath("favicons/apple-touch-icon-120x120.png");?>">
	<link rel="apple-touch-icon" sizes="144x144" href="<?=$this->basePath("favicons/apple-touch-icon-144x144.png");?>">
	<link rel="apple-touch-icon" sizes="152x152" href="<?=$this->basePath("favicons/apple-touch-icon-152x152.png");?>">
	<link rel="apple-touch-icon" sizes="180x180" href="<?=$this->basePath("favicons/apple-touch-icon-180x180.png");?>">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/favicon-32x32.png");?>" sizes="32x32">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/android-chrome-192x192.png");?>" sizes="192x192">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/favicon-96x96.png");?>" sizes="96x96">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/favicon-16x16.png");?>" sizes="16x16">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/favicon-16x16.png");?>">

	<?= $this->headLink()
		->appendStylesheet( $this->basePath() . '/stylesheets/screen.css' )
		->appendStylesheet( $this->basePath() . '/stylesheets/ie.css','screen','IE 9')
	; ?>

	<?= $this->headScript()
		->appendFile(
			$this->basePath('/vendor/jquery/dist/jquery.min.js'),
			'text/javascript'
		)->appendFile(
			$this->basePath('/vendor/fluidbox/jquery.fluidbox.min.js'),
			'text/javascript'
		)->appendFile(
			'http://maps.googleapis.com/maps/api/js?sensor=false',
			'text/javascript'
		)->appendFile(
			$this->basePath('/vendor/html5shiv/dist/html5shiv.js'),
			'text/javascript',
			array('conditional' => 'IE 9')
		)->appendFile(
			$this->basePath('/javascripts/polyfills.js'),
			'text/javascript',
			array('conditional' => 'IE 9')
		)
	;?>



</head>
	<body class="state-logout">
		<main role="main">
			<header class="main__header">
				<h1 class="main__brand">
					<a href="/">Stjórnvísi</a>
					<a href="#" class="main__burger"><i class="icon-burger"></i></a>
				</h1>
				<nav class="main__menu">
					<ul class="main__menu-items">
						<li><a href="<?php echo $this->url('vidburdir') ?>">Viðburðir</a></li>
						<li><a href="<?php echo $this->url('frettir') ?>">Fréttir</a></li>
						<li><a href="<?php echo $this->url('hopur') ?>">Hópar</a></li>
						<li><a href="<?php echo $this->url('stjornunarverdlaunin') ?>">Stjónunarverðlaunin</a></li>
						<li><a href="<?php echo $this->url('anaegjuvogin') ?>">Ánægjuvogin</a></li>
					</ul>
				</nav>
				<!--form method="get" action="<?=$this->url('leita')?>" class="main__search">
					<input name="q" type="search" placeholder="Leit..." />
					<input type="submit" value="leita">
				</form-->
			</header>

			<?= $this->content; ?>


		</main>
		<footer role="footer">
			<div class="footer-wrapper">
				<div class="footer-wrapper__inner">
					<div class="footer-wrapper__item footer-wrapper__address">
						<h1 class="footer-wrapper__brand">Stjórnvísi ehf</h1>
						<p>Innovation House</p>
						<p>Eiðistorgi 13-17 170 Seltjarnarnes</p>
						<p>Kt: 650686-1609</p>
						<p><a href="mailto:stjornvisi@stjornvisi.is">stjornvisi@stjornvisi.is</a></p>
						<p>Sími: 533-5666 Gsm: 840-4990</p>
					</div>
					<ul class="footer-wrapper__item">
						<li><a href="<?php echo $this->url('um') ?>">Um Stjórnvísi</a></li>
						<li><a href="<?php echo $this->url('stjornin') ?>">Stjórnin</a></li>
						<li><a href="<?php echo $this->url('log-arsskyrslur-og-arsreikningar') ?>">Lög, ársskýrslur og ársreikningar</a></li>
						<li><a href="/">Fundagerðir</a></li>
						<li><a href="<?php echo $this->url('kennsla') ?>">Handbók vefsins og kennslumyndbönd</a></li>
						<li><a href="<?php echo $this->url('fyrirtaeki') ?>">Fyrirtæki innan Stjórnvísi</a></li>
					</ul>
					<ul class="footer-wrapper__item">
						<li><a href="<?php echo $this->url('hopur') ?>">Hópar</a></li>
						<li><a href="<?php echo $this->url('vidburdir') ?>">Viðburðir</a></li>
						<li><a href="<?php echo $this->url('frettir') ?>">Fréttir</a></li>
						<li><a href="<?php echo $this->url('greinar') ?>">Greinar</a></li>
					</ul>
				</div>
			</div>
		</footer>
		<?php $this->headScript()->deleteContainer();?>
		<?=$this->headScript()->appendFile(
			$this->basePath('/javascripts/common.js'),
			'text/javascript'
		);?>
		<?= $this->inlineScript() ?>
	</body>
</html>
