<?php
/**
 * Created by PhpStorm.
 * User: einar
 * Date: 29/09/14
 * Time: 14:25
 */

?>

<table style="width:100%; font-family:sans-serif;font-size:14px" cellpadding="0" cellspacing="0">
	<tr style="background-color:#292468">
		<td width="10%">&nbsp;</td>
		<td >
			<img src="/stjornvisi/stylesheets//images/header-logo.png" alt="Stjónvísi">
		</td>
		<td width="10%">&nbsp;</td>
	</tr>
	<tr>
		<td width="10%">&nbsp;</td>
		<td style="background-color:#f6f7fb"><?php echo $this->content; ?></td>
		<td width="10%">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td style="text-align:center; font-size:12px; padding:15px">
			Stjórnvísi | Innovation house | Eiðistorgi 13-17 170 Seltjarnarnes<br />
			Kt: 650686-1609 | stjornvisi@stjornvisi.is | Sími: 533-5666 Gsm: 840-4990
		</td>
		<td>&nbsp;</td>
	</tr>
</table>
