<?php
/**
 * Created by PhpStorm.
 * User: einar
 * Date: 29/09/14
 * Time: 14:25
 */

?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta charset="utf-8">
	<title></title>
</head>
<body style="margin: 0; padding: 0;">
<table cellpadding="0" cellspacing="0" class="container" style="border-collapse: collapse; width: 100%; height: 100%; background: rgb(240,240,240);" bgcolor="rgb(240,240,240)">
	<tr>
		<td> </td>
		<td> </td>
		<td> </td>
	</tr>
	<tr>
		<td> </td>
		<td>
			<center>
				<img src="/stjornvisi/stylesheets/images/mail-logo.png" width="290" height="215" template="true">
			</center>
		</td>
		<td> </td>
	</tr>
	<tr>
		<td style="width: 10%;"> </td>
		<td class="content" style="width: 80%; background: white; padding: 30px; border: 1px solid rgb(230,230,230);" bgcolor="white"><?php echo $this->content; ?></td>
		<td style="width: 10%;"> </td>
	</tr>
	<tr>
		<td> </td>
		<td class="footnodes" style="font-family: Verdana, Geneva, sans-serif; text-align: center; font-size: 10px; color: rgb(139, 139, 139); padding: 60px;" align="center">
			STJÓRNVÍSI EHF
			Innovation House
			Eiðistorgi 13-15 170 Seltjarnarnes<br>
			Kt: 650686-1609
			Sími: 533-5666 Gsm: 840-4990<br><a href="mailto:stjornvisi@stjornvisi.is" style="text-decoration: none; color: rgb(139, 139, 139);">stjornvisi@stjornvisi.is</a> |
			<a href="http://stjornvisi.is" style="text-decoration: none; color: rgb(139, 139, 139);">stjornvisi.is</a>
		</td>
		<td> </td>
	</tr>
</table>
</body>
</html>
