<?php
/**
 * Created by PhpStorm.
 * User: einar
 * Date: 25/01/15
 * Time: 15:22
 */
?>
<?php echo $this->doctype(); ?>
<html lang="is">
<head>
	<meta charset="utf-8">
	<?=$this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
	<meta name="msapplication-TileColor" content="#292468">
	<meta name="msapplication-TileImage" content="<?=$this->basePath("favicons/mstile-144x144.png");?>">
	<meta name="theme-color" content="#292468">

	<?=$this->headTitle('Stjórnvísi ')->setSeparator(' / ')->setAutoEscape(false)?>

	<link rel="apple-touch-icon" sizes="57x57" href="<?=$this->basePath("favicons/apple-touch-icon-57x57.png");?>">
	<link rel="apple-touch-icon" sizes="60x60" href="<?=$this->basePath("favicons/apple-touch-icon-60x60.png");?>">
	<link rel="apple-touch-icon" sizes="72x72" href="<?=$this->basePath("favicons/apple-touch-icon-72x72.png");?>">
	<link rel="apple-touch-icon" sizes="76x76" href="<?=$this->basePath("favicons/apple-touch-icon-76x76.png");?>">
	<link rel="apple-touch-icon" sizes="114x114" href="<?=$this->basePath("favicons/apple-touch-icon-114x114.png");?>">
	<link rel="apple-touch-icon" sizes="120x120" href="<?=$this->basePath("favicons/apple-touch-icon-120x120.png");?>">
	<link rel="apple-touch-icon" sizes="144x144" href="<?=$this->basePath("favicons/apple-touch-icon-144x144.png");?>">
	<link rel="apple-touch-icon" sizes="152x152" href="<?=$this->basePath("favicons/apple-touch-icon-152x152.png");?>">
	<link rel="apple-touch-icon" sizes="180x180" href="<?=$this->basePath("favicons/apple-touch-icon-180x180.png");?>">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/favicon-32x32.png");?>" sizes="32x32">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/android-chrome-192x192.png");?>"
		  sizes="192x192">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/favicon-96x96.png");?>" sizes="96x96">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/favicon-16x16.png");?>" sizes="16x16">
	<link rel="icon" type="image/png" href="<?=$this->basePath("favicons/favicon-16x16.png");?>">

	<?=$this->headLink()
		->appendStylesheet('https://fonts.googleapis.com/css?family=Lato:300,400,600,700')
		->appendStylesheet($this->basePath() . '/themes/2016/stylesheets/screen.css')
		->appendStylesheet($this->basePath() . '/themes/2016/stylesheets/ie.css', 'screen', 'IE 9')
		->appendStylesheet($this->basePath() . '/vendor/OwlCarousel2/dist/assets/owl.carousel.css', 'screen')
	;?>

	<?= $this->headScript()
		->appendFile(
			$this->basePath('/vendor/jquery/dist/jquery.min.js'),
			'text/javascript'
		)->appendFile(
			$this->basePath('/vendor/OwlCarousel2/dist/owl.carousel.min.js'),
			'text/javascript'
		)
	;?>
</head>
<body class="state-landing">

<main role="main">
	<?php echo $this->content; ?>
</main>

<?=$this->partial('layout/_footer.phtml')?>

<?=$this->headScript()->appendFile($this->basePath('/javascripts/common.js'), 'text/javascript');?>
<?=$this->inlineScript()?>
<script type="text/javascript">
	$(function () {
		$('.owl-carousel').owlCarousel({
			loop:false,
			margin:10,
			nav:true,
			navText:['<i class="fa fa-chevron-circle-left"></i>', '<i class="fa fa-chevron-circle-right"></i>'],
			touchDrag  : false,
			mouseDrag  : false,
			responsive:{
				0:{
					items:1
				},
				600:{
					items:1
				},
				1000:{
					items:2
				}
			}
		})
	});

	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-24585167-1']);
	_gaq.push(['_trackPageview']);

	(function () {
		var ga = document.createElement('script');
		ga.type = 'text/javascript';
		ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0];
		s.parentNode.insertBefore(ga, s);
	})();

</script>
</body>
</html>
