<?php echo $this->doctype(); ?>
<html lang="is">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Stjórnvísi '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
		<script src="<?=$this->basePath();?>/vendor/webcomponentsjs/webcomponents.min.js"></script>
		<script src="<?=$this->basePath();?>/vendor/html5shiv/dist/html5shiv.js"></script>
		<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
		<link rel="import" href="<?=$this->basePath();?>/webcomponents/components.html">
        <!-- Le styles -->
        <?php echo $this->headLink(array(
			'rel' => 'icon',
			'type' => 'image/png',
			'href' => $this->basePath() . '/styles/img/favicon.png')
			)
			->appendStylesheet( $this->basePath() . '/stylesheets//screen.css' )
			->appendStylesheet( $this->basePath() . '/stylesheets//ie.css','screen','IE 9')
		; ?>
    </head>
	<body class="state-login">
		<nav role="navigation">
			<div class="navigation__wrapper">
				<?=$this->subMenu()?>
			</div>

			<ul class="categories">
				<li><a href="/" class="categories__home" title="Heim">heim</a></li>
				<li><a href="#" class="categories__groups" title="Faghópar">groups</a></li>
				<!--li><a class="news control" href="" title="Fréttir">news</a></li-->
				<!--li><a class="events control" href="" title="Viðburðir">events</a></li-->
				<li><a href="#" class="categories__users" title="Notendur">user</a></li>
				<li><a href="#" class="categories__config" title="Stillingar">config</a></li>
			</ul>
		</nav>

		<main role="main">
			<header class="main__header">
				<h1 class="main__brand">Stjórnvísi</h1>
				<nav class="main__menu">
					<ul class="main__menu-items">
						<li><a href="<?php echo $this->url('vidburdir') ?>">Viðburðir</a></li>
						<li><a href="<?php echo $this->url('frettir') ?>">Fréttir</a></li>
						<li><a href="<?php echo $this->url('hopur') ?>">Hópar</a></li>
						<li><a href="<?php echo $this->url('stjornunarverdlaunin') ?>">Stjónunarverðlaunin</a></li>
						<li><a href="<?php echo $this->url('anaegjuvogin') ?>">Ánægjuvogin</a></li>
					</ul>
				</nav>
				<form method="get" action="<?=$this->url('leita')?>" class="main__search">
					<input name="q" type="search" placeholder="Leit..." />
					<input type="submit" value="leita">
				</form>
			</header>
			<?php echo $this->content; ?>
		</main>

		<footer role="footer">
			<div class="footer-wrapper">
				<div class="footer-wrapper__inner">
					<div class="footer-wrapper__item">
						<h1>Stjórnvísi</h1>
						<p>Innovation house</p>
						<p>Eiðistorgi 13-17 170 Seltjarnarnes</p>
						<p>Kt: 650686-1609</p>
						<p><a href="mailto:stjornvisi@stjornvisi.is">stjornvisi@stjornvisi.is</a></p>
						<p>Sími: 533-5666 Gsm: 840-4990</p>
					</div>
					<ul class="footer-wrapper__item">
						<li><a href="<?php echo $this->url('um') ?>">Um Stjórnvísi</a></li>
						<li><a href="<?php echo $this->url('stjornin') ?>">Stjórnin</a></li>
						<li><a href="<?php echo $this->url('log-arsskyrslur-og-arsreikningar') ?>">Lög, ársskýrslur og ársreikningar</a></li>
						<li><a href="/">Fundagerðir</a></li>
						<li><a href="<?php echo $this->url('kennsla') ?>">Handbók vefsins og kennslumyndbönd</a></li>
						<li><a href="<?php echo $this->url('fyrirtaeki') ?>">Fyrirtæki innan Stjórnvísi</a></li>
					</ul>
					<ul class="footer-wrapper__item">
						<li><a href="<?php echo $this->url('vidburdir') ?>">Viðburðir</a></li>
						<li><a href="<?php echo $this->url('frettir') ?>">Fréttir</a></li>
						<li><a href="<?php echo $this->url('greinar') ?>">Greinar</a></li>
						<li><a href="<?php echo $this->url('hopur') ?>">Hópar</a></li>
					</ul>
				</div>
			</div>
		</footer>
		<?php echo $this->inlineScript() ?>
		<!-- Scripts -->
		<?php echo $this->headScript()
			//->appendFile($this->basePath() . '/vendor/html5shiv-dist/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
			->appendFile($this->basePath() . '/javascripts/common.js')
		; ?>
	<script>
		var active = undefined;
		document.querySelector('.categories__groups').addEventListener('click',function(event){
			event.preventDefault();
			document.querySelector('ul.navigation').style.marginLeft = 0;
			if(active == undefined){
				event.target.classList.add('active');
				document.body.classList.add('state-open');
				active = event.target;
			}
			else if( active == event.target ){
				event.target.classList.remove('active');
				document.body.classList.remove('state-open');
				active = undefined;
			}else{
				active.classList.remove('active');
				active = event.target;
				active.classList.add('active');
			}


		},false);
		document.querySelector('.categories__users').addEventListener('click',function(event){
			event.preventDefault();
			document.querySelector('ul.navigation').style.marginLeft = '-100%';
			if(active == undefined){
				event.target.classList.add('active');
				document.body.classList.add('state-open');
				active = event.target;
			}
			else if( active == event.target ){
				event.target.classList.remove('active');
				document.body.classList.remove('state-open');
				active = undefined;
			}else{
				active.classList.remove('active');
				active = event.target;
				active.classList.add('active');
			}
		},false);
		document.querySelector('.categories__config').addEventListener('click',function(event){
			event.preventDefault();
			document.querySelector('ul.navigation').style.marginLeft = '-200%';
			if(active == undefined){
				event.target.classList.add('active');
				document.body.classList.add('state-open');
				active = event.target;
			}
			else if( active == event.target ){
				event.target.classList.remove('active');
				document.body.classList.remove('state-open');
				active = undefined;
			}else{
				active.classList.remove('active');
				active = event.target;
				active.classList.add('active');
			}
		},false);

	</script>
	</body>
</html>
